// AUTO-GENERATED BY KIRO
// Accessibility utilities and constants

/**
 * ARIA live region announcements for screen readers
 */
export function announceToScreenReader(message: string, priority: "polite" | "assertive" = "polite") {
  const liveRegion = document.getElementById("aria-live-region") || createLiveRegion();
  liveRegion.setAttribute("aria-live", priority);
  liveRegion.textContent = message;
  
  // Clear after announcement
  setTimeout(() => {
    liveRegion.textContent = "";
  }, 1000);
}

function createLiveRegion(): HTMLElement {
  const region = document.createElement("div");
  region.id = "aria-live-region";
  region.setAttribute("aria-live", "polite");
  region.setAttribute("aria-atomic", "true");
  region.className = "sr-only";
  region.style.cssText = "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0;";
  document.body.appendChild(region);
  return region;
}

/**
 * Keyboard navigation helpers
 */
export const KEYBOARD_KEYS = {
  ENTER: "Enter",
  SPACE: " ",
  ESCAPE: "Escape",
  ARROW_UP: "ArrowUp",
  ARROW_DOWN: "ArrowDown",
  ARROW_LEFT: "ArrowLeft",
  ARROW_RIGHT: "ArrowRight",
  TAB: "Tab",
  HOME: "Home",
  END: "End",
} as const;

/**
 * Handle keyboard events for interactive elements
 */
export function handleKeyboardNavigation(
  event: React.KeyboardEvent,
  callbacks: {
    onEnter?: () => void;
    onEscape?: () => void;
    onArrowUp?: () => void;
    onArrowDown?: () => void;
    onArrowLeft?: () => void;
    onArrowRight?: () => void;
  }
) {
  switch (event.key) {
    case KEYBOARD_KEYS.ENTER:
    case KEYBOARD_KEYS.SPACE:
      event.preventDefault();
      callbacks.onEnter?.();
      break;
    case KEYBOARD_KEYS.ESCAPE:
      callbacks.onEscape?.();
      break;
    case KEYBOARD_KEYS.ARROW_UP:
      event.preventDefault();
      callbacks.onArrowUp?.();
      break;
    case KEYBOARD_KEYS.ARROW_DOWN:
      event.preventDefault();
      callbacks.onArrowDown?.();
      break;
    case KEYBOARD_KEYS.ARROW_LEFT:
      event.preventDefault();
      callbacks.onArrowLeft?.();
      break;
    case KEYBOARD_KEYS.ARROW_RIGHT:
      event.preventDefault();
      callbacks.onArrowRight?.();
      break;
  }
}

/**
 * Focus management utilities
 */
export function trapFocus(element: HTMLElement) {
  const focusableElements = element.querySelectorAll<HTMLElement>(
    'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])'
  );
  
  const firstElement = focusableElements[0];
  const lastElement = focusableElements[focusableElements.length - 1];

  return {
    firstElement,
    lastElement,
    handleTabKey: (e: KeyboardEvent) => {
      if (e.key !== KEYBOARD_KEYS.TAB) return;

      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          e.preventDefault();
          lastElement?.focus();
        }
      } else {
        if (document.activeElement === lastElement) {
          e.preventDefault();
          firstElement?.focus();
        }
      }
    },
  };
}

/**
 * Screen reader only text (visually hidden but accessible)
 */
export function srOnly(className?: string) {
  return `sr-only ${className || ""}`;
}

/**
 * Check if user prefers reduced motion
 */
export function prefersReducedMotion(): boolean {
  if (typeof window === "undefined") return false;
  return window.matchMedia("(prefers-reduced-motion: reduce)").matches;
}

/**
 * Get accessible color contrast ratio
 * Returns true if contrast meets WCAG AA standards (4.5:1 for normal text)
 */
export function hasGoodContrast(foreground: string, background: string): boolean {
  // Simplified check - in production, use a proper contrast calculation library
  // This is a placeholder
  return true;
}

