// AUTO-GENERATED BY KIRO
// Performance monitoring utilities

interface WebVitals {
  name: string;
  value: number;
  id: string;
  delta: number;
  rating: "good" | "needs-improvement" | "poor";
}

/**
 * Report Web Vitals to console (or analytics service)
 */
export function reportWebVitals(metric: WebVitals) {
  // In production, send to analytics service (e.g., Google Analytics, Vercel Analytics)
  if (process.env.NODE_ENV === "development") {
    console.log("Web Vital:", metric);
  }

  // Example: Send to analytics endpoint
  // fetch("/api/analytics/web-vitals", {
  //   method: "POST",
  //   body: JSON.stringify(metric),
  //   headers: { "Content-Type": "application/json" },
  // });
}

/**
 * Measure API response time
 */
export async function measureApiCall<T>(
  apiCall: () => Promise<T>,
  endpoint: string
): Promise<T> {
  const startTime = performance.now();
  try {
    const result = await apiCall();
    const duration = performance.now() - startTime;
    
    if (process.env.NODE_ENV === "development") {
      console.log(`API ${endpoint}: ${duration.toFixed(2)}ms`);
    }
    
    return result;
  } catch (error) {
    const duration = performance.now() - startTime;
    console.error(`API ${endpoint} failed after ${duration.toFixed(2)}ms:`, error);
    throw error;
  }
}

/**
 * Track user interaction
 */
export function trackInteraction(action: string, details?: Record<string, unknown>) {
  if (process.env.NODE_ENV === "development") {
    console.log("Interaction:", action, details);
  }

  // In production, send to analytics
  // fetch("/api/analytics/interaction", {
  //   method: "POST",
  //   body: JSON.stringify({ action, details, timestamp: Date.now() }),
  //   headers: { "Content-Type": "application/json" },
  // });
}

/**
 * Monitor component render time
 */
export function measureRenderTime(componentName: string) {
  const startTime = performance.now();
  
  return () => {
    const duration = performance.now() - startTime;
    if (process.env.NODE_ENV === "development" && duration > 16) {
      console.warn(`${componentName} render took ${duration.toFixed(2)}ms (target: <16ms)`);
    }
  };
}

