// AUTO-GENERATED BY KIRO
// Web Vitals tracking for performance monitoring

import { onCLS, onFID, onLCP, onFCP, onTTFB } from "web-vitals";
import { reportWebVitals } from "./performance";

/**
 * Initialize Web Vitals tracking
 */
export function initWebVitals() {
  if (typeof window === "undefined") return;

  // Cumulative Layout Shift (CLS)
  onCLS((metric) => {
    reportWebVitals({
      name: metric.name,
      value: metric.value,
      id: metric.id,
      delta: metric.delta,
      rating: metric.rating as "good" | "needs-improvement" | "poor",
    });
  });

  // First Input Delay (FID)
  onFID((metric) => {
    reportWebVitals({
      name: metric.name,
      value: metric.value,
      id: metric.id,
      delta: metric.delta,
      rating: metric.rating as "good" | "needs-improvement" | "poor",
    });
  });

  // Largest Contentful Paint (LCP)
  onLCP((metric) => {
    reportWebVitals({
      name: metric.name,
      value: metric.value,
      id: metric.id,
      delta: metric.delta,
      rating: metric.rating as "good" | "needs-improvement" | "poor",
    });
  });

  // First Contentful Paint (FCP)
  onFCP((metric) => {
    reportWebVitals({
      name: metric.name,
      value: metric.value,
      id: metric.id,
      delta: metric.delta,
      rating: metric.rating as "good" | "needs-improvement" | "poor",
    });
  });

  // Time to First Byte (TTFB)
  onTTFB((metric) => {
    reportWebVitals({
      name: metric.name,
      value: metric.value,
      id: metric.id,
      delta: metric.delta,
      rating: metric.rating as "good" | "needs-improvement" | "poor",
    });
  });
}

