// AUTO-GENERATED BY KIRO
// Web Vitals tracking for performance monitoring
// NOTE: Requires 'web-vitals' package to be installed: npm install web-vitals

import { reportWebVitals } from "./performance";

/**
 * Initialize Web Vitals tracking
 * Only works if web-vitals package is installed
 */
export function initWebVitals() {
  if (typeof window === "undefined") return;

  // Try to import web-vitals dynamically (optional dependency)
  // @ts-ignore - web-vitals is optional
  import("web-vitals")
    .then(({ onCLS, onFID, onLCP, onFCP, onTTFB }) => {
      // Cumulative Layout Shift (CLS)
      onCLS((metric: any) => {
        reportWebVitals({
          name: metric.name,
          value: metric.value,
          id: metric.id,
          delta: metric.delta,
          rating: metric.rating as "good" | "needs-improvement" | "poor",
        });
      });

      // First Input Delay (FID)
      onFID((metric: any) => {
        reportWebVitals({
          name: metric.name,
          value: metric.value,
          id: metric.id,
          delta: metric.delta,
          rating: metric.rating as "good" | "needs-improvement" | "poor",
        });
      });

      // Largest Contentful Paint (LCP)
      onLCP((metric: any) => {
        reportWebVitals({
          name: metric.name,
          value: metric.value,
          id: metric.id,
          delta: metric.delta,
          rating: metric.rating as "good" | "needs-improvement" | "poor",
        });
      });

      // First Contentful Paint (FCP)
      onFCP((metric: any) => {
        reportWebVitals({
          name: metric.name,
          value: metric.value,
          id: metric.id,
          delta: metric.delta,
          rating: metric.rating as "good" | "needs-improvement" | "poor",
        });
      });

      // Time to First Byte (TTFB)
      onTTFB((metric: any) => {
        reportWebVitals({
          name: metric.name,
          value: metric.value,
          id: metric.id,
          delta: metric.delta,
          rating: metric.rating as "good" | "needs-improvement" | "poor",
        });
      });
    })
    .catch(() => {
      // web-vitals not installed, silently fail
      if (process.env.NODE_ENV === "development") {
        console.log("web-vitals package not installed. Performance tracking disabled.");
      }
    });
}

