#!/bin/bash
# AUTO-GENERATED BY KIRO
# LoRA Training Script for Fashion Fusion System
# Fine-tune Stable Diffusion to learn garment structure

set -e

# Configuration
MODEL_NAME="runwayml/stable-diffusion-v1-5"
DATASET_PATH="./data/training"
OUTPUT_DIR="./models/lora"
CATEGORY="${1:-lehenga}"  # lehenga, blouse, gown, saree, etc.

# Training parameters
LEARNING_RATE=1e-4
BATCH_SIZE=1
NUM_EPOCHS=10
STEPS_PER_EPOCH=1000
SAVE_STEPS=500

# LoRA parameters
RANK=16
ALPHA=32

echo "Starting LoRA training for category: $CATEGORY"
echo "Dataset path: $DATASET_PATH/$CATEGORY"
echo "Output directory: $OUTPUT_DIR/$CATEGORY"

# Check if dataset exists
if [ ! -d "$DATASET_PATH/$CATEGORY" ]; then
    echo "Error: Dataset not found at $DATASET_PATH/$CATEGORY"
    echo "Please run train_dataset_prep.py first to prepare the dataset"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR/$CATEGORY"

# Activate virtual environment if exists
if [ -d "venv" ]; then
    source venv/bin/activate
fi

# Install dependencies if needed
if ! command -v accelerate &> /dev/null; then
    echo "Installing dependencies..."
    pip install accelerate peft diffusers transformers torch torchvision
fi

# Run training
python -m accelerate.commands.launch \
    --num_processes=1 \
    --mixed_precision=fp16 \
    train_lora.py \
    --pretrained_model_name_or_path="$MODEL_NAME" \
    --train_data_dir="$DATASET_PATH/$CATEGORY" \
    --output_dir="$OUTPUT_DIR/$CATEGORY" \
    --resolution=512 \
    --train_batch_size=$BATCH_SIZE \
    --learning_rate=$LEARNING_RATE \
    --max_train_steps=$((NUM_EPOCHS * STEPS_PER_EPOCH)) \
    --save_steps=$SAVE_STEPS \
    --lora_rank=$RANK \
    --lora_alpha=$ALPHA \
    --mixed_precision="fp16" \
    --gradient_accumulation_steps=4 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=100

echo "Training complete! Model saved to $OUTPUT_DIR/$CATEGORY"

