// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { PublicLayout } from "@/components/PublicLayout";
import { FusionWorkspace } from "@/components/FusionWorkspace";
import { JudgeTestMode } from "@/components/JudgeTestMode";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";

export default function Fusion() {
  const [judgeTestMode, setJudgeTestMode] = useState(
    process.env.NODE_ENV === "development" || 
    new URLSearchParams(window.location.search).get("judge") === "true"
  );

  return (
    <PublicLayout>
      <div className="min-h-screen bg-background">
        <div className="container mx-auto px-4 pt-4">
          {/* Judge Test Mode Toggle */}
          <Card className="p-4 mb-4 border-[var(--neon-stitch)]/50">
            <div className="flex items-center justify-between">
              <div className="space-y-1">
                <Label htmlFor="judge-mode" className="text-sm font-medium">
                  Judge Test Mode
                </Label>
                <p className="text-xs text-muted-foreground">
                  Preload test images and highlight Kiro integration
                </p>
              </div>
              <Switch
                id="judge-mode"
                checked={judgeTestMode}
                onCheckedChange={setJudgeTestMode}
                aria-label="Toggle Judge Test Mode"
              />
            </div>
          </Card>

          {/* Judge Test Mode Panel */}
          <JudgeTestMode enabled={judgeTestMode} onToggle={setJudgeTestMode} />
        </div>

        <FusionWorkspace judgeTestMode={judgeTestMode} />
      </div>
    </PublicLayout>
  );
}

