// AUTO-GENERATED BY KIRO
import { useState, useEffect } from "react";
import { PublicLayout } from "@/components/PublicLayout";
import { CategorySelector } from "@/components/CategorySelector";
import { FabricUploader } from "@/components/FabricUploader";
import { FusionOptions } from "@/components/FusionOptions";
import { FusionProgress } from "@/components/FusionProgress";
import { FusionResults } from "@/components/FusionResults";
import { TryOnCanvas } from "@/components/TryOnCanvas";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ChevronRight, ChevronLeft, Sparkles } from "lucide-react";
import type { GarmentCategory, FusionMode } from "../../../shared/schema.js";
import { api } from "@/lib/api";

type Step = "category" | "upload" | "options" | "generate" | "results";

export default function Fusion() {
  const [step, setStep] = useState<Step>("category");
  const [category, setCategory] = useState<GarmentCategory | undefined>();
  const [fabricTop, setFabricTop] = useState<string>();
  const [fabricBottom, setFabricBottom] = useState<string>();
  const [fabricTrims, setFabricTrims] = useState<string>();
  const [referenceModel, setReferenceModel] = useState<string>();
  const [mode, setMode] = useState<FusionMode>("hybrid");
  const [strength, setStrength] = useState(0.5);
  const [stitchStyle, setStitchStyle] = useState<string>("none");
  const [embroideryToggle, setEmbroideryToggle] = useState(false);
  const [faceConsent, setFaceConsent] = useState(false);
  const [faceDetected, setFaceDetected] = useState(false);
  const [jobId, setJobId] = useState<string>();
  const [jobStatus, setJobStatus] = useState<"pending" | "processing" | "completed" | "failed">("pending");
  const [jobProgress, setJobProgress] = useState(0);
  const [jobError, setJobError] = useState<string>();
  const [jobResult, setJobResult] = useState<any>();
  const [uploading, setUploading] = useState<string | null>(null);

  // Poll job status
  useEffect(() => {
    if (!jobId || jobStatus === "completed" || jobStatus === "failed") return;

    const interval = setInterval(async () => {
      try {
        const data = await api.get(`/api/fusion/status/${jobId}`);
        setJobStatus(data.status);
        setJobProgress(data.progress);
        setJobError(data.error);
        if (data.status === "completed") {
          setJobResult(data);
          setStep("results");
        } else if (data.status === "failed") {
          setStep("generate");
        }
      } catch (error) {
        console.error("Status check error:", error);
      }
    }, 2000);

    return () => clearInterval(interval);
  }, [jobId, jobStatus]);

  const handleUpload = async (type: "top" | "bottom" | "trims" | "reference", file: File) => {
    setUploading(type);
    try {
      const formData = new FormData();
      formData.append("images", file);

      const data = await api.post("/api/fusion/upload", formData);

      if (data.success && data.images && data.images.length > 0) {
        const url = data.images[0].url;
        if (type === "top") setFabricTop(url);
        else if (type === "bottom") setFabricBottom(url);
        else if (type === "trims") setFabricTrims(url);
        else if (type === "reference") setReferenceModel(url);

        // Check for faces (simplified - would call face detection API)
        // setFaceDetected(true); // Would be set based on API response
      }
    } catch (error: any) {
      console.error("Upload error:", error);
      throw new Error(error.message || "Upload failed");
    } finally {
      setUploading(null);
    }
  };

  const handleRemove = (type: "top" | "bottom" | "trims" | "reference") => {
    if (type === "top") setFabricTop(undefined);
    else if (type === "bottom") setFabricBottom(undefined);
    else if (type === "trims") setFabricTrims(undefined);
    else if (type === "reference") setReferenceModel(undefined);
  };

  const handleCreateFusion = async () => {
    if (!category || (!fabricTop && !fabricBottom && !fabricTrims)) {
      alert("Please select a category and upload at least one fabric image");
      return;
    }

    // Check if faces detected but no consent given
    if (faceDetected && !faceConsent) {
      alert("Please provide consent for face masking to proceed with images containing faces.");
      return;
    }

    setStep("generate");
    setJobStatus("pending");
    setJobProgress(0);

    try {
      const data = await api.post("/api/fusion/create", {
        category,
        fabricTop,
        fabricBottom,
        fabricTrims,
        referenceModel,
        mode,
        strength,
        stitchStyle,
        embroideryToggle,
        userConsent: faceConsent,
      });

      if (data.success) {
        setJobId(data.jobId);
        setJobStatus("processing");
      } else {
        throw new Error(data.error || "Failed to create fusion job");
      }
    } catch (error: any) {
      console.error("Create fusion error:", error);
      setJobError(error.message || "Failed to create fusion job");
      setJobStatus("failed");
    }
  };

  const canProceed = () => {
    if (step === "category") return !!category;
    if (step === "upload") return !!(fabricTop || fabricBottom || fabricTrims);
    if (step === "options") return true;
    return false;
  };

  return (
    <PublicLayout>
      <div className="min-h-screen bg-background py-8">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="mb-8 text-center">
            <h1 className="text-4xl font-bold mb-2 flex items-center justify-center gap-2">
              <Sparkles className="h-8 w-8" />
              Fashion Fusion Studio
            </h1>
            <p className="text-muted-foreground">
              Create photorealistic mannequin images with your fabric designs
            </p>
          </div>

          {/* Stepper */}
          <div className="mb-8">
            <div className="flex items-center justify-between">
              {(["category", "upload", "options", "generate"] as Step[]).map((s, idx) => (
                <div key={s} className="flex items-center flex-1">
                  <div
                    className={`flex items-center justify-center w-10 h-10 rounded-full border-2 ${
                      step === s
                        ? "border-primary bg-primary text-primary-foreground"
                        : idx < (["category", "upload", "options", "generate"] as Step[]).indexOf(step)
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-muted text-muted-foreground"
                    }`}
                  >
                    {idx + 1}
                  </div>
                  {idx < 3 && (
                    <div
                      className={`flex-1 h-1 mx-2 ${
                        idx < (["category", "upload", "options", "generate"] as Step[]).indexOf(step)
                          ? "bg-primary"
                          : "bg-muted"
                      }`}
                    />
                  )}
                </div>
              ))}
            </div>
            <div className="flex justify-between mt-2 text-xs text-muted-foreground">
              <span>Category</span>
              <span>Upload</span>
              <span>Options</span>
              <span>Generate</span>
            </div>
          </div>

          {/* Step Content */}
          <Card className="mb-4">
            <CardContent className="p-6">
              {step === "category" && (
                <CategorySelector value={category} onChange={setCategory} />
              )}

              {step === "upload" && (
                <FabricUploader
                  fabricTop={fabricTop}
                  fabricBottom={fabricBottom}
                  fabricTrims={fabricTrims}
                  referenceModel={referenceModel}
                  onUpload={handleUpload}
                  onRemove={handleRemove}
                  faceDetected={faceDetected}
                  onConsentChange={setFaceConsent}
                />
              )}

              {step === "options" && (
                <FusionOptions
                  mode={mode}
                  strength={strength}
                  stitchStyle={stitchStyle}
                  embroideryToggle={embroideryToggle}
                  onModeChange={setMode}
                  onStrengthChange={setStrength}
                  onStitchStyleChange={setStitchStyle}
                  onEmbroideryToggle={setEmbroideryToggle}
                  faceDetected={faceDetected}
                  faceConsent={faceConsent}
                  onFaceConsentChange={setFaceConsent}
                />
              )}

              {step === "generate" && (
                <div className="space-y-4">
                  <FusionProgress
                    status={jobStatus}
                    progress={jobProgress}
                    error={jobError}
                  />
                  {jobStatus === "failed" && (
                    <Button onClick={handleCreateFusion} className="w-full">
                      Retry Generation
                    </Button>
                  )}
                </div>
              )}

              {step === "results" && jobResult && (
                <Tabs defaultValue="result" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="result">Results</TabsTrigger>
                    <TabsTrigger value="tryon">Try-On</TabsTrigger>
                  </TabsList>
                  <TabsContent value="result">
                    <FusionResults
                      job={jobResult}
                      onRegenerate={() => {
                        setStep("options");
                        setJobId(undefined);
                        setJobResult(undefined);
                      }}
                    />
                  </TabsContent>
                  <TabsContent value="tryon">
                    <TryOnCanvas resultUrl={jobResult.resultUrl} />
                  </TabsContent>
                </Tabs>
              )}
            </CardContent>
          </Card>

          {/* Navigation */}
          {step !== "generate" && step !== "results" && (
            <div className="flex justify-between">
              <Button
                variant="outline"
                onClick={() => {
                  const steps: Step[] = ["category", "upload", "options", "generate"];
                  const currentIdx = steps.indexOf(step);
                  if (currentIdx > 0) setStep(steps[currentIdx - 1]);
                }}
                disabled={step === "category"}
              >
                <ChevronLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
              <Button
                onClick={() => {
                  if (step === "options") {
                    handleCreateFusion();
                  } else {
                    const steps: Step[] = ["category", "upload", "options", "generate"];
                    const currentIdx = steps.indexOf(step);
                    if (currentIdx < steps.length - 1) setStep(steps[currentIdx + 1]);
                  }
                }}
                disabled={!canProceed()}
              >
                {step === "options" ? "Create Fusion" : "Next"}
                <ChevronRight className="h-4 w-4 ml-2" />
              </Button>
            </div>
          )}
        </div>
      </div>
    </PublicLayout>
  );
}
