// AUTO-GENERATED BY KIRO
// Enhanced Fusion Pipeline for Fashion Garment Assembly
// REVIEW REQUIRED: Face detection and masking policy
// REVIEW REQUIRED: API key management

import { v2 as cloudinary } from "cloudinary";
import { storage } from "./storage.js";
import type { FusionJob, GarmentCategory, FusionMode } from "../shared/schema.js";
import { detectFaces, checkFaceProtection } from "./faceProtect.js";
import { segmentImageHF, generateImageHF, upscaleImageHF, extractCLIPFeatures } from "./models/huggingface.js";
import { segmentImageBytez, extractEdgesBytez } from "./models/bytez.js";
import { generateImageReplicate } from "./models/replicate.js";
import { analyzeWithFashionPedia, getGarmentParts } from "./models/fashionpedia.js";
import { extractGarmentRegions } from "./models/dresscode.js";
import { Readable } from "stream";

const USE_MOCK = process.env.NODE_ENV === "mock" || (!process.env.HUGGINGFACE_API_KEY && !process.env.BYTEZ_API_KEY);

// Mannequin templates per category (canonical poses)
// Store as public_ids (without version numbers) to avoid URL transformation issues
const MANNEQUIN_TEMPLATES: Record<GarmentCategory, string> = {
  lehenga: "fusion/mannequins/lehenga_template",
  blouse: "fusion/mannequins/blouse_template",
  gown: "fusion/mannequins/gown_template",
  saree: "fusion/mannequins/saree_template",
  salwar: "fusion/mannequins/salwar_template",
  dress: "fusion/mannequins/dress_template",
  top: "fusion/mannequins/top_template",
  skirt: "fusion/mannequins/skirt_template",
  other: "fusion/mannequins/generic_template",
};

interface ImageFeatures {
  palette: string[]; // Hex colors
  dominantPattern: string;
  motifPatches?: Array<{ url: string; x: number; y: number; width: number; height: number }>;
  clipEmbedding?: number[];
}

interface FabricFeatures {
  top?: ImageFeatures;
  bottom?: ImageFeatures;
  trims?: ImageFeatures;
}

/**
 * Extract color palette from image using node-vibrant (mock for now)
 */
async function extractPalette(imageUrl: string): Promise<string[]> {
  // TODO: Use node-vibrant or similar library
  // For now, return mock palette
  return ["#ff6b6b", "#9b59ff", "#ff8fb1", "#0b0f12"];
}

/**
 * Extract dominant pattern/motif description
 * Enhanced with FashionPedia integration
 */
async function extractPattern(imageUrl: string): Promise<string> {
  try {
    // Try FashionPedia first for better pattern detection
    const analysis = await analyzeWithFashionPedia(imageUrl);
    if (analysis.attributes.patterns && analysis.attributes.patterns.length > 0) {
      return analysis.attributes.patterns[0];
    }
  } catch (error) {
    console.warn("FashionPedia pattern extraction failed, using fallback:", error);
  }
  
  // Fallback: Use CLIP or simple pattern recognition
  return "paisley";
}

/**
 * Extract features from fabric images
 * Enhanced with FashionPedia integration for better attribute detection
 * Uses FashionPedia dataset structure - NO Python required!
 */
export async function extractFabricFeatures(
  fabricTop?: string,
  fabricBottom?: string,
  fabricTrims?: string,
  category?: string
): Promise<FabricFeatures> {
  const features: FabricFeatures = {};

  if (fabricTop) {
    const [palette, pattern, embedding, fashionPedia] = await Promise.all([
      extractPalette(fabricTop),
      extractPattern(fabricTop),
      extractCLIPFeatures(fabricTop).catch(() => []),
      analyzeWithFashionPedia(fabricTop, category).catch(() => null),
    ]);
    
    // Use FashionPedia attributes if available
    const finalPattern = fashionPedia?.attributes.patterns?.[0] || pattern;
    const material = fashionPedia?.attributes.materials?.[0] || "cotton";
    
    features.top = {
      palette,
      dominantPattern: `${finalPattern} (${material})`,
      clipEmbedding: embedding,
    };
  }

  if (fabricBottom) {
    const [palette, pattern, embedding, fashionPedia] = await Promise.all([
      extractPalette(fabricBottom),
      extractPattern(fabricBottom),
      extractCLIPFeatures(fabricBottom).catch(() => []),
      analyzeWithFashionPedia(fabricBottom, category).catch(() => null),
    ]);
    
    const finalPattern = fashionPedia?.attributes.patterns?.[0] || pattern;
    const material = fashionPedia?.attributes.materials?.[0] || "cotton";
    
    features.bottom = {
      palette,
      dominantPattern: `${finalPattern} (${material})`,
      clipEmbedding: embedding,
    };
  }

  if (fabricTrims) {
    const [palette, pattern, embedding, fashionPedia] = await Promise.all([
      extractPalette(fabricTrims),
      extractPattern(fabricTrims),
      extractCLIPFeatures(fabricTrims).catch(() => []),
      analyzeWithFashionPedia(fabricTrims, category).catch(() => null),
    ]);
    
    const finalPattern = fashionPedia?.attributes.patterns?.[0] || pattern;
    
    features.trims = {
      palette,
      dominantPattern: finalPattern,
      clipEmbedding: embedding,
    };
  }

  return features;
}

/**
 * Check if a Cloudinary resource exists
 */
async function checkCloudinaryResource(publicId: string): Promise<boolean> {
  try {
    // Only check if Cloudinary is configured
    if (!process.env.CLOUDINARY_CLOUD_NAME || !process.env.CLOUDINARY_API_KEY || !process.env.CLOUDINARY_API_SECRET) {
      console.warn("Cloudinary not configured, skipping resource check");
      return false;
    }
    
    const result = await cloudinary.api.resource(publicId, {
      resource_type: "image",
    });
    return !!result;
  } catch (error: any) {
    // Resource doesn't exist or API error
    if (error?.http_code === 404) {
      return false;
    }
    // For other errors (network, auth, etc.), assume it might exist (don't block)
    // This allows the system to continue even if the API check fails
    console.warn(`Could not verify Cloudinary resource ${publicId}:`, error.message || error);
    return false;
  }
}

/**
 * Get mannequin template for category
 * Returns Cloudinary URL from public_id, or null if resource doesn't exist
 */
async function getMannequinTemplate(category: GarmentCategory): Promise<string | null> {
  const publicId = MANNEQUIN_TEMPLATES[category] || MANNEQUIN_TEMPLATES.other;
  
  // Check if resource exists
  const exists = await checkCloudinaryResource(publicId);
  if (!exists) {
    console.warn(`Mannequin template ${publicId} not found in Cloudinary`);
    return null;
  }
  
  // Generate clean URL from public_id (no transformations)
  return cloudinary.url(publicId, {
    secure: true,
    resource_type: "image",
  });
}

/**
 * Construct prompt for fusion mode
 */
function constructPrompt(
  category: GarmentCategory,
  fabricFeatures: FabricFeatures,
  mode: FusionMode,
  referenceModel?: string
): { prompt: string; negativePrompt: string } {
  const negativePrompt = "no faces, no text, no logos, no watermarks, avoid surreal distortions, distorted faces, low quality, blurry, distorted shapes, extra limbs, missing limbs, bad anatomy, deformed, ugly, duplicate, mutilated";

  const fabricTopDesc = fabricFeatures.top
    ? `top fabric: ${fabricFeatures.top.dominantPattern} pattern in colors ${fabricFeatures.top.palette.slice(0, 3).join(", ")}`
    : "";
  const fabricBottomDesc = fabricFeatures.bottom
    ? `bottom fabric: ${fabricFeatures.bottom.dominantPattern} pattern in colors ${fabricFeatures.bottom.palette.slice(0, 3).join(", ")}`
    : "";
  const fabricTrimsDesc = fabricFeatures.trims
    ? `trims/buttons/motif: ${fabricFeatures.trims.dominantPattern} in ${fabricFeatures.trims.palette.slice(0, 2).join(", ")}`
    : "";

  const fabricDescription = [fabricTopDesc, fabricBottomDesc, fabricTrimsDesc].filter(Boolean).join("; ");

  if (mode === "silhouette-first") {
    return {
      prompt: `Photorealistic full-body ${category} garment on the canonical mannequin. Preserve the silhouette, pose, and drape of the mannequin. Apply texture and color palette from the uploaded fabric images: ${fabricDescription}. Keep seams natural and realistic fabric folds. Maintain skin tones and do NOT alter face. Wearable couture — realistic lighting and shadows.`,
      negativePrompt,
    };
  } else if (mode === "texture-first") {
    return {
      prompt: `Photorealistic garment emphasizing fabric motif fidelity. Transfer the exact pattern and texture from the uploaded fabrics (${fabricDescription}) onto the target garment region(s). Ensure the pattern placement is coherent and repeats naturally. Keep silhouette consistent but allow texture to define final shape. No face changes.`,
      negativePrompt,
    };
  } else {
    // hybrid
    return {
      prompt: `Balanced fusion: preserve silhouette while integrating strong motif & color cues from fabrics (${fabricDescription}). Ensure realistic seams and shading. Photorealistic ${category} on mannequin with natural drape. No face changes.`,
      negativePrompt,
    };
  }
}

/**
 * Upload blob to Cloudinary
 */
async function uploadToCloudinary(blob: Blob, folder: string = "fusion/results"): Promise<string> {
  return new Promise(async (resolve, reject) => {
    try {
      const arrayBuffer = await blob.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      const uploadStream = cloudinary.uploader.upload_stream(
        {
          folder,
          resource_type: "image",
          transformation: [{ quality: "auto:best" }],
        },
        (error, result) => {
          if (error) reject(error);
          else resolve(result!.secure_url);
        }
      );
      uploadStream.end(buffer);
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate image using model (with retry and fallback)
 */
async function generateImageWithModel(
  initImage: string,
  prompt: string,
  negativePrompt: string,
  controlnetImage: string,
  mode: FusionMode,
  strength: number,
  fabricImages?: { top?: string; bottom?: string; trims?: string }
): Promise<string> {
  const strengthMap: Record<FusionMode, number> = {
    "silhouette-first": 0.35,
    "texture-first": 0.6,
    "hybrid": 0.5,
  };

  const adjustedStrength = strengthMap[mode] || strength;
  const guidanceScale = 7.5;
  const steps = 25;

  // Retry logic with exponential backoff
  const maxRetries = 3;
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    // Try HuggingFace first
    try {
      if (process.env.HUGGINGFACE_API_KEY && !USE_MOCK) {
        const blob = await generateImageHF(
          initImage,
          prompt,
          negativePrompt,
          controlnetImage,
          {
            strength: adjustedStrength,
            guidanceScale,
            steps,
            controlnetWeight: mode === "silhouette-first" ? 1.0 : 0.8,
          }
        );
        return await uploadToCloudinary(blob);
      }
    } catch (error: any) {
      lastError = error;
      console.warn(`HF generation attempt ${attempt + 1} failed:`, error.message);
      if (attempt < maxRetries - 1) {
        await new Promise(resolve => setTimeout(resolve, Math.pow(2, attempt) * 1000));
        continue;
      }
    }

    // Try Replicate
    try {
      if (process.env.REPLICATE_API_TOKEN && !USE_MOCK) {
        return await generateImageReplicate(
          initImage,
          prompt,
          negativePrompt,
          controlnetImage,
          {
            strength: adjustedStrength,
            guidanceScale,
            steps,
          }
        );
      }
    } catch (error: any) {
      lastError = error;
      console.warn(`Replicate generation attempt ${attempt + 1} failed:`, error.message);
      if (attempt < maxRetries - 1) {
        await new Promise(resolve => setTimeout(resolve, Math.pow(2, attempt) * 1000));
        continue;
      }
    }
  }

  // Mock fallback (always works for demo)
  console.log("Using mock fusion generation (all API attempts failed or mock mode)");
  return generateMockFusion(initImage, controlnetImage, adjustedStrength, fabricImages);
}

/**
 * Create a placeholder mannequin image using Cloudinary text/image generation
 * This is used when no mannequin template exists
 */
function createPlaceholderMannequin(category: GarmentCategory): string {
  // Use Cloudinary's text overlay to create a simple mannequin placeholder
  // In production, you'd upload actual mannequin images
  const categoryText = category.charAt(0).toUpperCase() + category.slice(1);
  return cloudinary.url("sample", {
    secure: true,
    resource_type: "image",
    transformation: [
      { width: 1024, height: 1536, crop: "fill", color: "#f0f0f0", background: "#f0f0f0" },
      { overlay: { font_family: "Arial", font_size: 80, text: `Mannequin%20${categoryText}`, color: "#999" }, gravity: "center", y: -100 },
      { overlay: { font_family: "Arial", font_size: 40, text: "Placeholder", color: "#ccc" }, gravity: "center", y: 0 },
    ],
  });
}

/**
 * Mock fusion generation (for demo/reliability)
 * Creates a visually transformed image by compositing fabric onto mannequin
 */
function generateMockFusion(initImage: string, controlnetImage: string, strength: number, fabricImages?: { top?: string; bottom?: string; trims?: string }): string {
  // initImage should always be a mannequin template now (we fixed the fallback)
  // If we have fabric images, composite them onto the mannequin
  const fabricToUse = fabricImages?.top || fabricImages?.bottom || fabricImages?.trims;
  
  const publicId = extractPublicId(initImage);
  if (!publicId) {
    // If not Cloudinary URL, return as-is
    return initImage;
  }

  // Ensure we have a clean public_id
  const cleanPublicId = publicId.split("/").filter(part => 
    !part.includes("c_") && 
    !part.includes("w_") && 
    !part.includes("h_") && 
    !part.includes("q_") &&
    !part.includes("v1") &&
    !part.includes("v2")
  ).join("/");

  if (!cleanPublicId) {
    return initImage;
  }

  // If we have fabric images, try to composite them
  if (fabricToUse) {
    const fabricId = extractPublicId(fabricToUse);
    if (fabricId) {
      const cleanFabricId = fabricId.split("/").filter(part => 
        !part.includes("c_") && 
        !part.includes("w_") && 
        !part.includes("h_") && 
        !part.includes("q_") &&
        !part.includes("v1") &&
        !part.includes("v2")
      ).join("/");
      
      if (cleanFabricId) {
        try {
          // Composite: mannequin base with fabric overlay
          return cloudinary.url(cleanPublicId, {
            secure: true,
            resource_type: "image",
            transformation: [
              { width: 1024, height: 1536, crop: "fill", quality: "auto:best" },
              {
                overlay: cleanFabricId,
                width: 1024,
                height: 1536,
                crop: "fill",
                opacity: Math.round(60 + strength * 20), // 60-80% opacity based on strength
                effect: "multiply", // Blend mode to make fabric appear on mannequin
              },
              { effect: `tint:${Math.round(strength * 20)}:FF6FB1` },
              { effect: "vibrance:30" },
              { effect: "saturation:20" },
            ],
          });
        } catch (error) {
          console.warn("Cloudinary composite failed, using simple transformation:", error);
        }
      }
    }
  }
  
  // Fallback: apply transformations to mannequin to show fabric influence
  const timestamp = Date.now();
  try {
    return cloudinary.url(cleanPublicId, {
      secure: true,
      resource_type: "image",
      transformation: [
        { width: 1024, height: 1536, crop: "fill", quality: "auto:best" },
        { effect: `tint:${Math.round(strength * 60)}:FF6FB1` },
        { effect: "vibrance:40" },
        { effect: "saturation:25" },
        { overlay: `text:Arial_50:Fusion+${timestamp % 1000}`, opacity: 0, gravity: "north_east" },
      ],
    });
  } catch (error) {
    console.warn("Cloudinary URL generation failed, using original image:", error);
    return initImage;
  }
}

/**
 * Extract edges for ControlNet
 */
async function extractEdges(imageUrl: string): Promise<string> {
  try {
    if (process.env.BYTEZ_API_KEY) {
      const edgeMap = await extractEdgesBytez(imageUrl, "canny");
      // Upload edge map to Cloudinary
      // For now, return original (would need to convert base64 to blob)
      return imageUrl;
    }
  } catch (error) {
    console.warn("Edge extraction failed:", error);
  }

  // Fallback: use Cloudinary edge detection
  const publicId = extractPublicId(imageUrl);
  if (publicId) {
    return cloudinary.url(publicId, {
      transformation: [
        { effect: "edge_detect:50" },
        { effect: "grayscale" },
      ],
    });
  }

  return imageUrl;
}

/**
 * Segment garment regions using SAM + Dress Code integration
 */
async function segmentGarmentRegions(
  mannequinImage: string,
  category: GarmentCategory
): Promise<{ topMask?: string; bottomMask?: string; fullMask: string }> {
  try {
    // Try Dress Code human parsing first (more accurate for garments)
    const dressCodeSeg = await extractGarmentRegions(mannequinImage, category);
    if (dressCodeSeg.garmentRegions.top || dressCodeSeg.garmentRegions.bottom || dressCodeSeg.garmentRegions.dress) {
      return {
        topMask: dressCodeSeg.garmentRegions.top,
        bottomMask: dressCodeSeg.garmentRegions.bottom,
        fullMask: dressCodeSeg.garmentRegions.dress || mannequinImage,
      };
    }
  } catch (error) {
    console.warn("Dress Code segmentation failed, trying SAM:", error);
  }

  try {
    // Fallback to SAM
    if (process.env.HUGGINGFACE_API_KEY) {
      const result = await segmentImageHF(mannequinImage, [
        { type: "box", coordinates: [0, 0, 512, 512] }, // Full image
      ]);
      // Process masks and return
    }
  } catch (error) {
    console.warn("SAM segmentation failed:", error);
  }

  // Return mock masks as last resort
  return {
    fullMask: mannequinImage,
  };
}

/**
 * Generate explainability data
 */
async function generateExplainability(
  fabricFeatures: FabricFeatures,
  resultUrl: string,
  category: GarmentCategory
): Promise<FusionJob["explainability"]> {
  // Extract CLIP embeddings from result
  const resultEmbedding = await extractCLIPFeatures(resultUrl).catch(() => []);

  const contributionRegions: Array<{
    region: string;
    contribution: number;
    pattern: string;
    fabricSource: "top" | "bottom" | "trims" | "reference";
  }> = [];

  // Match fabric embeddings to result regions
  if (fabricFeatures.top && fabricFeatures.top.clipEmbedding) {
    // Calculate similarity (simplified)
    const similarity = 0.8; // Would calculate actual cosine similarity
    contributionRegions.push({
      region: category === "lehenga" ? "Blouse" : "Top",
      contribution: similarity,
      pattern: fabricFeatures.top.dominantPattern,
      fabricSource: "top",
    });
  }

  if (fabricFeatures.bottom && fabricFeatures.bottom.clipEmbedding) {
    contributionRegions.push({
      region: category === "lehenga" ? "Skirt" : "Bottom",
      contribution: 0.7,
      pattern: fabricFeatures.bottom.dominantPattern,
      fabricSource: "bottom",
    });
  }

  if (fabricFeatures.trims) {
    contributionRegions.push({
      region: "Trims/Details",
      contribution: 0.5,
      pattern: fabricFeatures.trims.dominantPattern,
      fabricSource: "trims",
    });
  }

  return {
    heatmap: "", // TODO: Generate actual heatmap
    designerNote: `Fused ${category} using ${contributionRegions.map(r => r.fabricSource).join(", ")} fabrics. ${contributionRegions.map(r => `${r.region}: ${r.pattern}`).join("; ")}.`,
    contributionRegions,
  };
}

/**
 * Upscale image using Real-ESRGAN or Cloudinary
 */
async function upscaleImage(imageUrl: string): Promise<string> {
  try {
    if (process.env.HUGGINGFACE_API_KEY) {
      const blob = await upscaleImageHF(imageUrl, 2);
      return await uploadToCloudinary(blob, "fusion/upscaled");
    }
  } catch (error) {
    console.warn("Real-ESRGAN upscaling failed, using Cloudinary:", error);
  }

  // Fallback to Cloudinary upscaling
  const publicId = extractPublicId(imageUrl);
  if (publicId) {
    return cloudinary.url(publicId, {
      transformation: [
        { quality: "auto:best", dpr: 2.0, width: 2048, height: 2048, crop: "limit" },
      ],
    });
  }

  return imageUrl;
}

/**
 * Extract Cloudinary public ID
 */
/**
 * Extract Cloudinary public ID from URL
 * Handles various Cloudinary URL formats including transformations
 */
function extractPublicId(url: string): string | null {
  try {
    if (url.includes("cloudinary.com")) {
      // If URL contains transformations (has slashes after /upload/), we need to extract differently
      // Pattern 1: /upload/[transformations]/[version]/[public_id]
      // Pattern 2: /upload/[version]/[public_id]
      // Pattern 3: /upload/[public_id]
      
      // First, try to find the public_id after the last transformation segment
      // Cloudinary URLs with transformations look like: /upload/t_xxx/v1/public_id
      const uploadMatch = url.match(/\/upload\/(.+?)(?:\?|$)/);
      if (uploadMatch && uploadMatch[1]) {
        const pathAfterUpload = uploadMatch[1];
        
        // Check if it has version number (v1, v2, etc.)
        const versionMatch = pathAfterUpload.match(/v\d+\/(.+?)(?:\?|$)/);
        if (versionMatch && versionMatch[1]) {
          // Has version number, extract public_id after it
          let publicId = versionMatch[1].split("?")[0];
          // Remove file extension
          publicId = publicId.replace(/\.(jpg|jpeg|png|webp|gif)$/i, "");
          return publicId;
        }
        
        // No version number, might be transformations or direct public_id
        // Check if it looks like transformations (contains underscores, colons, etc.)
        if (pathAfterUpload.includes("c_") || pathAfterUpload.includes("w_") || pathAfterUpload.includes("h_")) {
          // This looks like transformations, try to find public_id after last slash
          const parts = pathAfterUpload.split("/");
          if (parts.length > 0) {
            const lastPart = parts[parts.length - 1].split("?")[0];
            const publicId = lastPart.replace(/\.(jpg|jpeg|png|webp|gif)$/i, "");
            // Only return if it doesn't look like a transformation parameter
            if (!publicId.includes(":") && (!publicId.includes("_") || publicId.includes("/"))) {
              return publicId;
            }
          }
        } else {
          // No transformations, treat as direct public_id
          let publicId = pathAfterUpload.split("?")[0];
          publicId = publicId.replace(/\.(jpg|jpeg|png|webp|gif)$/i, "");
          return publicId;
        }
      }
    }
    return null;
  } catch (e) {
    console.error("Error extracting public ID:", e);
    return null;
  }
}

/**
 * Main fusion pipeline
 */
export async function processFusionJob(jobId: string): Promise<void> {
  const job = await storage.getFusionJob(jobId);
  if (!job) {
    throw new Error(`Fusion job ${jobId} not found`);
  }

  try {
    // Update status to processing
    await storage.updateFusionJob(jobId, {
      status: "processing",
      progress: 5,
    });

    // Step 1: Face detection & protection (REVIEW REQUIRED)
    const imageUrls: string[] = [];
    if (job.fabricTop) imageUrls.push(job.fabricTop);
    if (job.fabricBottom) imageUrls.push(job.fabricBottom);
    if (job.fabricTrims) imageUrls.push(job.fabricTrims);
    if (job.referenceModel) imageUrls.push(job.referenceModel);
    // Legacy support
    if (job.imageA) imageUrls.push(job.imageA);
    if (job.imageB) imageUrls.push(job.imageB);

    // Pass user consent to face protection check
    const faceCheck = await checkFaceProtection(imageUrls, job.userConsent);
    if (faceCheck.requiresProtection && !faceCheck.protected) {
      await storage.updateFusionJob(jobId, {
        status: "failed",
        error: faceCheck.error || "Faces detected. Please provide consent for face masking or use images without faces.",
        progress: 0,
      });
      return;
    }

    await storage.updateFusionJob(jobId, {
      progress: 10,
      metadata: { ...job.metadata, faceProtected: faceCheck.protected },
    });

    // Step 2: Get mannequin template
    // Use reference model if provided, otherwise use category template, or create placeholder
    let mannequinTemplate = job.referenceModel;
    if (!mannequinTemplate) {
      const templateUrl = await getMannequinTemplate(job.category);
      if (templateUrl) {
        mannequinTemplate = templateUrl;
      } else {
        // Template doesn't exist, create a placeholder mannequin
        // This ensures we always have a mannequin base, not just fabric
        mannequinTemplate = createPlaceholderMannequin(job.category);
        console.log(`Mannequin template not found, using placeholder for category: ${job.category}`);
      }
    }
    
    // Ensure we have fabric images to apply
    if (!job.fabricTop && !job.fabricBottom && !job.fabricTrims && !job.imageA && !job.imageB) {
      throw new Error("At least one fabric image is required to create the fusion");
    }
    
    await storage.updateFusionJob(jobId, { progress: 15 });

    // Step 3: Extract fabric features
    // Ensure we have at least one fabric image
    if (!job.fabricTop && !job.fabricBottom && !job.fabricTrims && !job.imageA && !job.imageB) {
      throw new Error("At least one fabric image is required");
    }
    
    // Extract features using FashionPedia structure (no Python needed!)
    const fabricFeatures = await extractFabricFeatures(
      job.fabricTop || job.imageA,
      job.fabricBottom || job.imageB,
      job.fabricTrims,
      job.category // Pass category for better FashionPedia mapping
    );

    await storage.updateFusionJob(jobId, {
      progress: 20,
      metadata: {
        ...job.metadata,
        paletteTop: fabricFeatures.top?.palette,
        paletteBottom: fabricFeatures.bottom?.palette,
        paletteTrims: fabricFeatures.trims?.palette,
        dominantPattern: fabricFeatures.top?.dominantPattern || fabricFeatures.bottom?.dominantPattern,
        garmentType: job.category,
        mannequinTemplate,
      },
    });

    // Step 4: Segment garment regions (SAM)
    const garmentMasks = await segmentGarmentRegions(mannequinTemplate, job.category);
    await storage.updateFusionJob(jobId, { progress: 25 });

    // Step 5: Extract edges for ControlNet
    const edgeMap = await extractEdges(mannequinTemplate);
    await storage.updateFusionJob(jobId, { progress: 30 });

    // Step 6: Generate 3 candidates (silhouette-first, texture-first, hybrid)
    const modes: FusionMode[] = ["silhouette-first", "texture-first", "hybrid"];
    const candidates: Array<{ url: string; mode: FusionMode; thumbnail?: string }> = [];

    for (let i = 0; i < modes.length; i++) {
      const mode = modes[i];
      console.log(`Generating candidate ${i + 1}/3 (${mode})...`);

      try {
        const { prompt, negativePrompt } = constructPrompt(
          job.category,
          fabricFeatures,
          mode,
          job.referenceModel
        );

        const candidateUrl = await generateImageWithModel(
          mannequinTemplate,
          prompt,
          negativePrompt,
          edgeMap,
          mode,
          job.strength,
          {
            top: job.fabricTop || job.imageA,
            bottom: job.fabricBottom || job.imageB,
            trims: job.fabricTrims,
          }
        );

        if (candidateUrl && candidateUrl !== mannequinTemplate) {
          candidates.push({
            url: candidateUrl,
            mode,
            thumbnail: candidateUrl,
          });
          await storage.updateFusionJob(jobId, {
            progress: 35 + (i + 1) * 15, // 35, 50, 65
            candidates: candidates.slice(),
          });
        } else {
          console.warn(`Candidate ${i + 1} generation returned invalid URL`);
        }
      } catch (error: any) {
        console.error(`Error generating candidate ${i + 1}:`, error);
        // Continue with other candidates
      }
    }

    // If no candidates generated, try one more time with hybrid mode
    if (candidates.length === 0) {
      console.log("No candidates generated, trying fallback...");
      try {
        const { prompt, negativePrompt } = constructPrompt(
          job.category,
          fabricFeatures,
          "hybrid",
          job.referenceModel
        );
        const fallbackUrl = await generateImageWithModel(
          mannequinTemplate,
          prompt,
          negativePrompt,
          edgeMap,
          "hybrid",
          job.strength,
          {
            top: job.fabricTop || job.imageA,
            bottom: job.fabricBottom || job.imageB,
            trims: job.fabricTrims,
          }
        );
        if (fallbackUrl) {
          candidates.push({ url: fallbackUrl, mode: "hybrid" });
        }
      } catch (error) {
        console.error("Fallback generation also failed:", error);
      }
      
      if (candidates.length === 0) {
        throw new Error("Failed to generate any fusion candidates. Please try again or check your API keys.");
      }
    }

    // Step 7: Select best candidate (use first for now, could add scoring)
    const resultUrl = candidates[0].url;
    await storage.updateFusionJob(jobId, {
      progress: 70,
      resultUrl,
    });

    // Step 8: Post-process (seam blending, color harmonization)
    // TODO: Implement seam blending
    await storage.updateFusionJob(jobId, { progress: 75 });

    // Step 9: Upscale
    const upscaledUrl = await upscaleImage(resultUrl);
    await storage.updateFusionJob(jobId, {
      progress: 85,
      resultUrl: upscaledUrl,
    });

    // Step 10: Generate explainability
    const explainability = await generateExplainability(
      fabricFeatures,
      upscaledUrl,
      job.category
    );

    await storage.updateFusionJob(jobId, {
      progress: 95,
      explainability,
    });

    // Step 11: Complete
    await storage.updateFusionJob(jobId, {
      status: "completed",
      progress: 100,
    });
  } catch (error: any) {
    console.error("Fusion pipeline error:", error);
    await storage.updateFusionJob(jobId, {
      status: "failed",
      error: error.message || "Fusion processing failed",
      progress: 0,
    });
  }
}

