// AUTO-GENERATED BY KIRO
// Bytez API wrapper for ML models
// REVIEW REQUIRED: API key management and rate limiting

// Get fetch function (node-fetch or global fetch)
async function getFetch() {
  try {
    // Try to use node-fetch if available (optional dependency)
    // @ts-ignore - node-fetch is optional
    const nodeFetch = await import("node-fetch").catch(() => null);
    if (nodeFetch) {
      return nodeFetch.default as any;
    }
  } catch {
    // Ignore
  }
  // Use global fetch (available in Node 18+)
  return globalThis.fetch;
}

const BYTEZ_API_URL = "https://api.bytez.com/v1";
const BYTEZ_API_KEY = process.env.BYTEZ_API_KEY;

export interface BytezModelResponse {
  output?: string; // Base64 image or URL
  error?: string;
}

/**
 * Call Bytez API for model inference
 */
export async function callBytezModel(
  modelId: string,
  inputs: Record<string, unknown>
): Promise<BytezModelResponse> {
  if (!BYTEZ_API_KEY) {
    throw new Error("BYTEZ_API_KEY not configured");
  }

  try {
    const fetchFn = await getFetch();
    const response = await fetchFn(`${BYTEZ_API_URL}/models/${modelId}/predict`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${BYTEZ_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ inputs }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Bytez API error: ${response.status} ${errorText}`);
    }

    const data = await response.json() as BytezModelResponse;
    return data;
  } catch (error: any) {
    console.error("Bytez API error:", error);
    throw error;
  }
}

/**
 * Face detection using Bytez (Hemg/Face-Mask-Detection or damo/retinaface)
 */
export async function detectFacesBytez(imageUrl: string): Promise<{
  hasFaces: boolean;
  faceCount: number;
  faces?: Array<{ x: number; y: number; width: number; height: number }>;
}> {
  try {
    // Use retinaface model on Bytez
    const result = await callBytezModel("damo/retinaface", {
      image: imageUrl,
    });

    // Parse response (adjust based on actual Bytez response format)
    if (result.error) {
      return { hasFaces: false, faceCount: 0 };
    }

    // Mock parsing - adjust based on actual API response
    const faces = (result.output as any)?.faces || [];
    return {
      hasFaces: faces.length > 0,
      faceCount: faces.length,
      faces: faces.map((f: any) => ({
        x: f.x || f[0],
        y: f.y || f[1],
        width: f.width || f[2],
        height: f.height || f[3],
      })),
    };
  } catch (error) {
    console.error("Bytez face detection error:", error);
    return { hasFaces: false, faceCount: 0 };
  }
}

/**
 * SAM segmentation using Bytez (facebook/sam-vit-base)
 */
export async function segmentImageBytez(
  imageUrl: string,
  prompts?: Array<{ type: "point" | "box"; coordinates: number[] }>
): Promise<{
  masks: Array<{ mask: string; score: number }>; // Base64 masks
}> {
  try {
    const result = await callBytezModel("facebook/sam-vit-base", {
      image: imageUrl,
      prompts: prompts || [],
    });

    return {
      masks: (result.output as any)?.masks || [],
    };
  } catch (error) {
    console.error("Bytez SAM segmentation error:", error);
    return { masks: [] };
  }
}

/**
 * ControlNet edge detection (canny-edge or hed)
 */
export async function extractEdgesBytez(
  imageUrl: string,
  edgeType: "canny" | "hed" = "canny"
): Promise<string> { // Returns base64 edge map
  try {
    const modelId = edgeType === "canny" 
      ? "lllyasviel/control_v11p_sd15_canny" 
      : "lllyasviel/control_v11p_sd15_hed";
    
    const result = await callBytezModel(modelId, {
      image: imageUrl,
      mode: "edge_detection",
    });

    return (result.output as any)?.edge_map || "";
  } catch (error) {
    console.error("Bytez edge extraction error:", error);
    throw error;
  }
}

