// AUTO-GENERATED BY KIRO
// Dress Code Integration - Using dataset structure WITHOUT Python requirements
// This uses the Dress Code label mappings directly, no Python needed!

/**
 * Dress Code Human Parsing Labels (from the dataset)
 * These are static mappings - no Python required!
 * 
 * From datasets/dress-code-main/data/labelmap.py
 */
export const DRESS_CODE_LABELS = {
  0: "background",
  1: "hat",
  2: "hair",
  3: "sunglasses",
  4: "upper_clothes", // Top/blouse region
  5: "skirt", // Skirt region
  6: "pants", // Pants region
  7: "dress", // Full dress region
  8: "belt",
  9: "left_shoe",
  10: "right_shoe",
  11: "head",
  12: "left_leg",
  13: "right_leg",
  14: "left_arm",
  15: "right_arm",
  16: "bag",
  17: "scarf",
} as const;

/**
 * Map our category to Dress Code label IDs
 * Uses the dataset structure directly
 */
export function getDressCodeLabelsForCategory(category: string): number[] {
  const labelMap: Record<string, number[]> = {
    lehenga: [4, 5], // upper_clothes + skirt
    blouse: [4], // upper_clothes
    gown: [7], // dress
    saree: [4, 5], // upper_clothes + skirt (approximation)
    dress: [7], // dress
    top: [4], // upper_clothes
    skirt: [5], // skirt
    salwar: [4, 6], // upper_clothes + pants
  };

  return labelMap[category] || [4]; // Default to upper_clothes
}

/**
 * Get garment region name from Dress Code label
 */
export function getRegionName(labelId: number): string {
  return DRESS_CODE_LABELS[labelId as keyof typeof DRESS_CODE_LABELS] || "unknown";
}

/**
 * Map Dress Code labels to our garment regions
 */
export function mapDressCodeToRegions(
  category: string
): {
  top?: number;
  bottom?: number;
  full?: number;
} {
  const regions: {
    top?: number;
    bottom?: number;
    full?: number;
  } = {};

  if (category === "lehenga" || category === "blouse") {
    regions.top = 4; // upper_clothes
  }

  if (category === "lehenga" || category === "skirt") {
    regions.bottom = 5; // skirt
  }

  if (category === "dress" || category === "gown") {
    regions.full = 7; // dress
  }

  return regions;
}

/**
 * Extract garment regions using Dress Code structure
 * This uses the label mappings - no Python model needed for structure!
 * 
 * For actual segmentation, you'd call:
 * - A pre-trained model API (HuggingFace, Bytez)
 * - Or use the Dress Code model via API
 * - Or use SAM with Dress Code label prompts
 */
export async function extractRegionsWithDressCodeStructure(
  imageUrl: string,
  category: string
): Promise<{
  topMask?: string;
  bottomMask?: string;
  fullMask?: string;
  labelIds: number[];
}> {
  // Get the label IDs for this category from the dataset structure
  const labelIds = getDressCodeLabelsForCategory(category);
  const regions = mapDressCodeToRegions(category);

  // For actual masks, you'd call a segmentation API/model
  // For now, return the structure based on category
  return {
    topMask: regions.top ? `mask_for_label_${regions.top}` : undefined,
    bottomMask: regions.bottom ? `mask_for_label_${regions.bottom}` : undefined,
    fullMask: regions.full ? `mask_for_label_${regions.full}` : undefined,
    labelIds,
  };
}

