// AUTO-GENERATED BY KIRO
// FashionPedia Integration for Enhanced Garment Analysis
// Uses FashionPedia dataset structure WITHOUT Python requirements
// Reads JSON files directly from the dataset folder

import { mapToFashionPediaCategory, getFashionPediaAttributes, analyzeWithFashionPediaStructure } from "./fashionpedia-integration.js";

// FashionPedia category mapping to our categories
const CATEGORY_MAP: Record<number, string> = {
  0: "blouse", // shirt, blouse
  1: "top", // top, t-shirt, sweatshirt
  2: "blouse", // sweater
  3: "blouse", // cardigan
  4: "blouse", // jacket
  6: "skirt", // pants (we map to skirt for lehenga context)
  7: "skirt", // shorts
  8: "skirt", // skirt
  9: "gown", // coat
  10: "dress", // dress
  11: "dress", // jumpsuit
};

// Pattern attributes from FashionPedia
const PATTERN_ATTRIBUTES: Record<number, string> = {
  306: "paisley",
  304: "floral",
  305: "geometric",
  298: "plain",
  299: "abstract",
  301: "check",
  302: "dot",
  307: "stripe",
  312: "leopard",
  313: "snakeskin",
};

// Material attributes
const MATERIAL_ATTRIBUTES: Record<number, string> = {
  261: "satin",
  259: "chiffon",
  260: "organza",
  238: "flannel",
  240: "denim",
  243: "velvet",
  244: "chintz",
  245: "crepe",
};

export interface FashionPediaAnalysis {
  category: string;
  attributes: {
    patterns: string[];
    materials: string[];
    silhouette?: string;
    neckline?: string;
    sleeve?: string;
  };
  segmentation?: {
    garmentMask: string; // Base64 or URL
    parts: Array<{ part: string; mask: string }>;
  };
}

/**
 * Analyze garment image using FashionPedia structure
 * Uses the dataset JSON files directly - NO Python required!
 */
export async function analyzeWithFashionPedia(
  imageUrl: string,
  category?: string
): Promise<FashionPediaAnalysis> {
  // Use the FashionPedia dataset structure (JSON files)
  // No Python installation needed!
  
  if (category) {
    const analysis = await analyzeWithFashionPediaStructure(imageUrl, category);
    
    return {
      category: category,
      attributes: {
        patterns: analysis.attributeNames.filter((name) =>
          ["paisley", "floral", "geometric", "stripe", "plain", "abstract"].some((p) =>
            name.toLowerCase().includes(p)
          )
        ),
        materials: analysis.attributeNames.filter((name) =>
          ["satin", "chiffon", "silk", "cotton", "denim"].some((m) =>
            name.toLowerCase().includes(m)
          )
        ),
      },
    };
  }

  // Default analysis
  return {
    category: "lehenga",
    attributes: {
      patterns: ["paisley", "floral"],
      materials: ["silk", "chiffon"],
    },
  };
}

/**
 * Get garment parts segmentation using FashionPedia
 */
export async function getGarmentParts(
  imageUrl: string,
  category: string
): Promise<Array<{ part: string; mask: string }>> {
  // FashionPedia provides 19 apparel parts:
  // hood, collar, lapel, epaulette, sleeve, garment belt, pocket, neckline, etc.
  
  // TODO: Call FashionPedia segmentation API
  // For now, return mock parts based on category
  
  const partsMap: Record<string, string[]> = {
    lehenga: ["blouse", "skirt", "pallu"],
    blouse: ["body", "sleeve", "collar", "neckline"],
    gown: ["bodice", "skirt", "sleeve"],
    saree: ["pallu", "body", "border"],
    dress: ["bodice", "skirt", "sleeve"],
  };
  
  const parts = partsMap[category] || ["body"];
  
  return parts.map((part) => ({
    part,
    mask: imageUrl, // Would be actual mask URL
  }));
}

/**
 * Extract pattern description from FashionPedia attributes
 */
export function extractPatternFromAttributes(attributeIds: number[]): string {
  for (const attId of attributeIds) {
    if (PATTERN_ATTRIBUTES[attId]) {
      return PATTERN_ATTRIBUTES[attId];
    }
  }
  return "plain";
}

/**
 * Extract material description from FashionPedia attributes
 */
export function extractMaterialFromAttributes(attributeIds: number[]): string {
  for (const attId of attributeIds) {
    if (MATERIAL_ATTRIBUTES[attId]) {
      return MATERIAL_ATTRIBUTES[attId];
    }
  }
  return "cotton";
}

/**
 * Map FashionPedia category to our category system
 * Uses the dataset structure
 */
export function mapFashionPediaCategory(categoryId: number): string {
  return CATEGORY_MAP[categoryId] || "other";
}

// Re-export integration functions
export { 
  mapToFashionPediaCategory, 
  getFashionPediaAttributes,
  analyzeWithFashionPediaStructure 
} from "./fashionpedia-integration.js";

