// AUTO-GENERATED BY KIRO
// FashionPedia Integration - Using dataset structure WITHOUT Python requirements
// This uses the FashionPedia JSON structure directly, no Python needed!

import fs from "fs";
import path from "path";

// Load FashionPedia category and attribute mappings from the dataset
// These are static JSON files, no Python required!
let fashionPediaData: any = null;

/**
 * Load FashionPedia data from the dataset JSON files
 * This reads the static JSON structure - no Python needed!
 */
function loadFashionPediaData() {
  if (fashionPediaData) return fashionPediaData;

  try {
    // Read the sample.json from the dataset
    const datasetPath = path.join(process.cwd(), "datasets", "fashionpedia-api-master", "data", "sample.json");
    if (fs.existsSync(datasetPath)) {
      const fileContent = fs.readFileSync(datasetPath, "utf-8");
      fashionPediaData = JSON.parse(fileContent);
      console.log("Loaded FashionPedia data from dataset");
    } else {
      console.warn("FashionPedia dataset not found, using default mappings");
      fashionPediaData = getDefaultFashionPediaData();
    }
  } catch (error) {
    console.error("Error loading FashionPedia data:", error);
    fashionPediaData = getDefaultFashionPediaData();
  }

  return fashionPediaData;
}

/**
 * Default FashionPedia mappings (from the dataset structure)
 * Extracted from the JSON files - no Python needed!
 */
function getDefaultFashionPediaData() {
  return {
    categories: [
      { id: 0, name: "shirt, blouse", supercategory: "upperbody" },
      { id: 1, name: "top, t-shirt, sweatshirt", supercategory: "upperbody" },
      { id: 6, name: "pants", supercategory: "lowerbody" },
      { id: 8, name: "skirt", supercategory: "lowerbody" },
      { id: 10, name: "dress", supercategory: "wholebody" },
      // ... more categories from the dataset
    ],
    attributes: [
      { id: 304, name: "floral", supercategory: "textile pattern" },
      { id: 305, name: "geometric", supercategory: "textile pattern" },
      { id: 306, name: "paisley", supercategory: "textile pattern" },
      { id: 307, name: "stripe", supercategory: "textile pattern" },
      { id: 261, name: "satin", supercategory: "woven" },
      { id: 259, name: "chiffon", supercategory: "woven" },
      // ... more attributes from the dataset
    ],
  };
}

/**
 * Map our category to FashionPedia category ID
 * Uses the dataset structure directly
 */
export function mapToFashionPediaCategory(ourCategory: string): number | null {
  const data = loadFashionPediaData();
  const categoryMap: Record<string, number> = {
    lehenga: 10, // dress (wholebody)
    blouse: 0, // shirt, blouse
    gown: 10, // dress
    saree: 10, // dress
    dress: 10,
    top: 1, // top, t-shirt
    skirt: 8,
    salwar: 6, // pants
  };

  return categoryMap[ourCategory] || null;
}

/**
 * Get FashionPedia attributes for a pattern/material
 * Uses the dataset attribute mappings
 */
export function getFashionPediaAttributes(pattern: string, material?: string): number[] {
  const data = loadFashionPediaData();
  const attrs: number[] = [];

  // Map pattern to attribute ID
  const patternMap: Record<string, number> = {
    paisley: 306,
    floral: 304,
    geometric: 305,
    stripe: 307,
    plain: 298,
    abstract: 299,
  };

  if (patternMap[pattern.toLowerCase()]) {
    attrs.push(patternMap[pattern.toLowerCase()]);
  }

  // Map material to attribute ID
  if (material) {
    const materialMap: Record<string, number> = {
      satin: 261,
      chiffon: 259,
      silk: 261, // Use satin as proxy
      cotton: 238, // flannel as proxy
      denim: 240,
    };

    if (materialMap[material.toLowerCase()]) {
      attrs.push(materialMap[material.toLowerCase()]);
    }
  }

  return attrs;
}

/**
 * Get category name from FashionPedia ID
 */
export function getCategoryName(categoryId: number): string {
  const data = loadFashionPediaData();
  const category = data.categories?.find((c: any) => c.id === categoryId);
  return category?.name || "unknown";
}

/**
 * Get attribute names from IDs
 */
export function getAttributeNames(attributeIds: number[]): string[] {
  const data = loadFashionPediaData();
  return attributeIds
    .map((id) => {
      const attr = data.attributes?.find((a: any) => a.id === id);
      return attr?.name;
    })
    .filter(Boolean);
}

/**
 * Analyze image using FashionPedia structure (without Python)
 * This uses the dataset mappings to understand garment properties
 */
export async function analyzeWithFashionPediaStructure(
  imageUrl: string,
  category: string
): Promise<{
  categoryId: number;
  suggestedAttributes: number[];
  attributeNames: string[];
}> {
  const categoryId = mapToFashionPediaCategory(category) || 10; // Default to dress

  // For now, return suggested attributes based on category
  // In production, you'd call an actual FashionPedia API or model
  const suggestedAttributes: number[] = [];

  if (category === "lehenga" || category === "saree") {
    suggestedAttributes.push(306); // paisley
    suggestedAttributes.push(304); // floral
    suggestedAttributes.push(261); // satin
  } else if (category === "blouse" || category === "top") {
    suggestedAttributes.push(305); // geometric
    suggestedAttributes.push(307); // stripe
  }

  return {
    categoryId,
    suggestedAttributes,
    attributeNames: getAttributeNames(suggestedAttributes),
  };
}

