// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import type { GarmentCategory } from "../../../shared/schema.js";

const CATEGORIES: Array<{ value: GarmentCategory; label: string; icon: string }> = [
  { value: "lehenga", label: "Lehenga", icon: "👗" },
  { value: "blouse", label: "Blouse", icon: "👔" },
  { value: "gown", label: "Gown", icon: "👘" },
  { value: "saree", label: "Saree", icon: "🧵" },
  { value: "salwar", label: "Salwar", icon: "👖" },
  { value: "dress", label: "Dress", icon: "👗" },
  { value: "top", label: "Top", icon: "👕" },
  { value: "skirt", label: "Skirt", icon: "👗" },
  { value: "other", label: "Other", icon: "✨" },
];

interface CategorySelectorProps {
  value?: GarmentCategory;
  onChange: (category: GarmentCategory) => void;
}

export function CategorySelector({ value, onChange }: CategorySelectorProps) {
  return (
    <div className="space-y-4">
      <Label className="text-lg font-semibold">Select Garment Category</Label>
      <div className="grid grid-cols-3 gap-4">
        {CATEGORIES.map((category) => (
          <Card
            key={category.value}
            className={`cursor-pointer transition-all ${
              value === category.value
                ? "border-2 border-primary bg-primary/10"
                : "border hover:border-primary/50"
            }`}
            onClick={() => onChange(category.value)}
          >
            <CardContent className="p-4 text-center">
              <div className="text-3xl mb-2">{category.icon}</div>
              <Label className="cursor-pointer">{category.label}</Label>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

