// AUTO-GENERATED BY KIRO
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Info } from "lucide-react";

interface ExplainabilityData {
  heatmap: string; // Base64 encoded overlay image
  designerNote: string;
  contributionRegions: Array<{
    region: string;
    contribution: number; // 0-1
    pattern: string;
  }>;
}

interface ExplainabilityPanelProps {
  explainability: ExplainabilityData;
}

export function ExplainabilityPanel({ explainability }: ExplainabilityPanelProps) {
  return (
    <Card className="kiro-glow">
      <CardHeader>
        <CardTitle className="text-sm font-medium flex items-center gap-2">
          <Info className="h-4 w-4" />
          Explainability
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Designer Note */}
        <div className="p-4 bg-muted rounded-lg border border-border">
          <p className="text-sm leading-relaxed italic text-foreground">
            "{explainability.designerNote}"
          </p>
        </div>

        {/* Heatmap Overlay Preview */}
        {explainability.heatmap && (
          <div className="relative aspect-square rounded-lg overflow-hidden border-2 border-border">
            <img
              src={`data:image/png;base64,${explainability.heatmap}`}
              alt="Contribution heatmap"
              className="w-full h-full object-cover"
              loading="lazy"
              decoding="async"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent" />
            <div className="absolute bottom-2 left-2 text-xs text-foreground bg-background/80 rounded px-2 py-1">
              Contribution Heatmap
            </div>
          </div>
        )}

        {/* Contribution Regions */}
        <div className="space-y-2">
          <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
            Pattern Contributions
          </h4>
          {explainability.contributionRegions.map((region, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between p-2 bg-muted rounded border border-border"
            >
              <div className="flex-1">
                <p className="text-sm font-medium">{region.region}</p>
                <p className="text-xs text-muted-foreground">{region.pattern}</p>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-24 h-2 bg-muted-foreground/20 rounded-full overflow-hidden">
                  <div
                    className="h-full kiro-gradient"
                    style={{ width: `${region.contribution * 100}%` }}
                  />
                </div>
                <Badge variant="outline" className="text-xs">
                  {(region.contribution * 100).toFixed(0)}%
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

