// AUTO-GENERATED BY KIRO
import { useState, useCallback } from "react";
import { useDropzone } from "react-dropzone";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { X, Upload, Image as ImageIcon } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface FabricUploaderProps {
  fabricTop?: string;
  fabricBottom?: string;
  fabricTrims?: string;
  referenceModel?: string;
  onUpload: (type: "top" | "bottom" | "trims" | "reference", file: File) => Promise<void>;
  onRemove: (type: "top" | "bottom" | "trims" | "reference") => void;
  faceDetected?: boolean;
  onConsentChange?: (consent: boolean) => void;
}

export function FabricUploader({
  fabricTop,
  fabricBottom,
  fabricTrims,
  referenceModel,
  onUpload,
  onRemove,
  faceDetected,
  onConsentChange,
}: FabricUploaderProps) {
  const [uploading, setUploading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const onDrop = useCallback(
    async (acceptedFiles: File[], type: "top" | "bottom" | "trims" | "reference") => {
      if (acceptedFiles.length === 0) return;

      const file = acceptedFiles[0];
      setUploading(type);
      setError(null);

      try {
        await onUpload(type, file);
      } catch (err: any) {
        setError(err.message || "Upload failed");
      } finally {
        setUploading(null);
      }
    },
    [onUpload]
  );

  const createDropzone = (type: "top" | "bottom" | "trims" | "reference") => {
    const { getRootProps, getInputProps, isDragActive } = useDropzone({
      onDrop: (files) => onDrop(files, type),
      accept: { "image/*": [".png", ".jpg", ".jpeg", ".webp"] },
      maxSize: 10 * 1024 * 1024, // 10MB
      multiple: false,
    });

    const label = {
      top: "Top Fabric",
      bottom: "Bottom Fabric",
      trims: "Trims/Buttons/Motif",
      reference: "Reference Model Dress (Optional)",
    }[type];

    const imageUrl = {
      top: fabricTop,
      bottom: fabricBottom,
      trims: fabricTrims,
      reference: referenceModel,
    }[type];

    const isUploading = uploading === type;

    return (
      <Card className="border-dashed">
        <CardContent className="p-4">
          <Label className="text-sm font-medium mb-2 block">{label}</Label>
          {imageUrl ? (
            <div className="relative">
              <img
                src={imageUrl}
                alt={label}
                className="w-full h-48 object-cover rounded-lg"
              />
              <Button
                variant="destructive"
                size="icon"
                className="absolute top-2 right-2"
                onClick={() => onRemove(type)}
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          ) : (
            <div
              {...getRootProps()}
              className={`border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors ${
                isDragActive
                  ? "border-primary bg-primary/10"
                  : "border-muted-foreground/50 hover:border-primary/50"
              } ${isUploading ? "opacity-50" : ""}`}
            >
              <input {...getInputProps()} />
              {isUploading ? (
                <div className="space-y-2">
                  <Upload className="h-8 w-8 mx-auto animate-pulse" />
                  <p className="text-sm text-muted-foreground">Uploading...</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <ImageIcon className="h-8 w-8 mx-auto text-muted-foreground" />
                  <p className="text-sm">
                    {isDragActive ? "Drop image here" : "Click or drag to upload"}
                  </p>
                  <p className="text-xs text-muted-foreground">PNG, JPG, WEBP up to 10MB</p>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="space-y-4">
      <Label className="text-lg font-semibold">Upload Fabric Images</Label>
      
      {faceDetected && (
        <Alert className="border-amber-500 bg-amber-50 dark:bg-amber-950/20">
          <AlertDescription>
            <div className="space-y-2">
              <p className="font-medium">Faces detected in uploaded images</p>
              <p className="text-sm">
                To protect privacy, faces will be automatically masked during processing.
              </p>
              <div className="flex items-center space-x-2">
                <input
                  type="checkbox"
                  id="face-consent"
                  onChange={(e) => onConsentChange?.(e.target.checked)}
                  className="rounded"
                />
                <Label htmlFor="face-consent" className="text-sm cursor-pointer">
                  I consent to face masking
                </Label>
              </div>
            </div>
          </AlertDescription>
        </Alert>
      )}

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {createDropzone("top")}
        {createDropzone("bottom")}
        {createDropzone("trims")}
        {createDropzone("reference")}
      </div>
    </div>
  );
}

