// AUTO-GENERATED BY KIRO
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { CheckCircle2, Loader2, XCircle } from "lucide-react";
import type { FusionJobStatus } from "../../../shared/schema.js";

interface FusionProgressProps {
  status: FusionJobStatus;
  progress: number;
  error?: string;
}

const STATUS_LABELS: Record<FusionJobStatus, string> = {
  pending: "Queued",
  processing: "Processing",
  completed: "Completed",
  failed: "Failed",
};

const STATUS_ICONS: Record<FusionJobStatus, React.ReactNode> = {
  pending: <Loader2 className="h-5 w-5 animate-spin" />,
  processing: <Loader2 className="h-5 w-5 animate-spin" />,
  completed: <CheckCircle2 className="h-5 w-5 text-green-500" />,
  failed: <XCircle className="h-5 w-5 text-red-500" />,
};

export function FusionProgress({ status, progress, error }: FusionProgressProps) {
  const steps = [
    { label: "Face Detection", progress: 10 },
    { label: "Feature Extraction", progress: 20 },
    { label: "Segmentation", progress: 30 },
    { label: "Edge Extraction", progress: 40 },
    { label: "Generating Candidates", progress: 70 },
    { label: "Post-Processing", progress: 85 },
    { label: "Upscaling", progress: 95 },
    { label: "Complete", progress: 100 },
  ];

  const currentStep = steps.find((step) => progress >= step.progress) || steps[0];

  return (
    <Card>
      <CardContent className="p-6 space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            {STATUS_ICONS[status]}
            <span className="font-semibold">{STATUS_LABELS[status]}</span>
          </div>
          <span className="text-sm text-muted-foreground">{progress}%</span>
        </div>

        <Progress value={progress} className="h-2" />

        {status === "processing" && (
          <div className="space-y-2">
            <p className="text-sm text-muted-foreground">{currentStep.label}</p>
            <div className="grid grid-cols-4 gap-2 text-xs">
              {steps.map((step, idx) => (
                <div
                  key={idx}
                  className={`p-2 rounded ${
                    progress >= step.progress
                      ? "bg-primary/10 text-primary"
                      : "bg-muted text-muted-foreground"
                  }`}
                >
                  {step.label}
                </div>
              ))}
            </div>
          </div>
        )}

        {status === "failed" && error && (
          <div className="p-3 bg-red-50 dark:bg-red-950/20 rounded-lg">
            <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

