// AUTO-GENERATED BY KIRO
import { useState, useCallback, useEffect } from "react";
import { useDropzone } from "react-dropzone";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Upload,
  Sparkles,
  Sliders,
  Play,
  Download,
  Share2,
  Grid3x3,
  Image as ImageIcon,
  Loader2,
  X,
  CheckCircle2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { MannequinCanvas } from "./MannequinCanvas";
import { ExplainabilityPanel } from "./ExplainabilityPanel";
import { LookbookGenerator } from "./LookbookGenerator";
import { SocialShareCard } from "./SocialShareCard";
import { FusionWorkspaceSkeleton } from "./Skeleton";
import { api } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";

interface FusionJob {
  jobId: string;
  status: "pending" | "processing" | "completed" | "failed";
  progress: number;
  resultUrl?: string;
  candidates?: string[];
  explainability?: {
    heatmap: string;
    designerNote: string;
    contributionRegions: Array<{
      region: string;
      contribution: number;
      pattern: string;
    }>;
  };
}

interface FusionWorkspaceProps {
  judgeTestMode?: boolean;
}

export function FusionWorkspace({ judgeTestMode = false }: FusionWorkspaceProps) {
  const { toast } = useToast();
  const [imageA, setImageA] = useState<string | null>(null);
  const [imageB, setImageB] = useState<string | null>(null);
  const [fusionMode, setFusionMode] = useState<"pattern" | "color" | "texture">("pattern");
  const [strength, setStrength] = useState([0.7]);
  const [currentJob, setCurrentJob] = useState<FusionJob | null>(null);

  // Upload mutation
  const uploadMutation = useMutation({
    mutationFn: async (files: File[]) => {
      const formData = new FormData();
      files.forEach((file) => formData.append("images", file));
      // Don't set Content-Type header - browser will set it with boundary automatically
      const response = await api.post("/api/fusion/upload", formData);
      return response;
    },
    onSuccess: (data) => {
      console.log("Upload response:", data);
      if (data.images && data.images.length > 0) {
        // If we have one image and imageA is not set, set imageA
        if (!imageA && data.images.length >= 1) {
          setImageA(data.images[0].url);
          toast({
            title: "First image uploaded",
            description: "Upload the second image to continue",
          });
        }
        // If we have two images, set both
        else if (data.images.length >= 2) {
          setImageA(data.images[0].url);
          setImageB(data.images[1].url);
          toast({
            title: "Images uploaded successfully",
            description: "Ready to create fusion",
          });
        }
        // If imageA is set and we get a new image, set it as imageB
        else if (imageA && data.images.length >= 1) {
          setImageB(data.images[0].url);
          toast({
            title: "Second image uploaded",
            description: "Ready to create fusion",
          });
        }
      }
    },
    onError: (error: any) => {
      toast({
        title: "Upload failed",
        description: error.message || "Please try again",
        variant: "destructive",
      });
    },
  });

  // Create fusion job mutation
  const createFusionMutation = useMutation({
    mutationFn: async () => {
      if (!imageA || !imageB) throw new Error("Both images required");
      const response = await api.post("/api/fusion/create", {
        imageA,
        imageB,
        mode: fusionMode,
        strength: strength[0],
      });
      return response;
    },
    onSuccess: (response) => {
      // API.post returns the JSON directly, so response is the result object
      const data = response;
      const jobId = data?.jobId || data?.id;
      
      console.log("Fusion job created, response:", response);
      
      if (!jobId) {
        console.error("Invalid response from server:", response);
        throw new Error("No job ID returned from server. Please try again.");
      }
      
      setCurrentJob({
        jobId: String(jobId),
        status: "pending",
        progress: 0,
      });
      toast({
        title: "Fusion job created",
        description: "Processing your fusion...",
      });
      // Poll for status
      pollJobStatus(String(jobId));
    },
    onError: (error: any) => {
      console.error("Fusion creation error:", error);
      const errorMessage = error?.response?.data?.error || error?.message || "Please try again";
      toast({
        title: "Failed to create fusion",
        description: errorMessage,
        variant: "destructive",
      });
    },
  });

  // Poll job status
  const pollJobStatus = useCallback(async (jobId: string) => {
    const interval = setInterval(async () => {
      try {
        const response = await api.get(`/api/fusion/status/${jobId}`);
        // API.get returns the JSON directly, so response is the job object
        const job = response;
        console.log("Polling job status:", job);
        
        if (!job) {
          console.error("No job data received");
          return;
        }
        
        setCurrentJob({
          jobId: job.jobId || jobId,
          status: job.status,
          progress: job.progress || 0,
          resultUrl: job.resultUrl,
          candidates: job.candidates || [],
          explainability: job.explainability,
        });

        if (job.status === "completed" || job.status === "failed") {
          clearInterval(interval);
          if (job.status === "completed") {
            // Fetch full results
            try {
              const resultsResponse = await api.get(`/api/fusion/results/${jobId}`);
              // API.get returns the JSON directly, so resultsResponse is the results object
              const results = resultsResponse;
              console.log("Fusion results:", results);
              setCurrentJob({
                jobId: results.jobId || jobId,
                status: results.status || "completed",
                progress: results.progress || 100,
                resultUrl: results.resultUrl || job.resultUrl,
                candidates: results.candidates || job.candidates || [],
                explainability: results.explainability || job.explainability,
              });
              toast({
                title: "Fusion completed!",
                description: "Your design is ready",
              });
            } catch (error) {
              console.error("Error fetching results:", error);
              // Use status data if results fetch fails
              setCurrentJob({
                jobId: job.jobId || jobId,
                status: job.status,
                progress: job.progress,
                resultUrl: job.resultUrl,
                candidates: job.candidates || [],
                explainability: job.explainability,
              });
            }
          } else if (job.status === "failed") {
            toast({
              title: "Fusion failed",
              description: job.error || "Please try again with different images",
              variant: "destructive",
            });
          }
        }
      } catch (error) {
        console.error("Error polling job status:", error);
        clearInterval(interval);
      }
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  // Dropzone for Image A
  const { getRootProps: getRootPropsA, getInputProps: getInputPropsA, isDragActive: isDragActiveA } =
    useDropzone({
      accept: { "image/*": [".png", ".jpg", ".jpeg", ".webp"] },
      maxFiles: 1,
      onDrop: (files) => {
        if (files[0]) {
          uploadMutation.mutate([files[0]]);
        }
      },
      disabled: uploadMutation.isPending,
    });

  // Dropzone for Image B
  const { getRootProps: getRootPropsB, getInputProps: getInputPropsB, isDragActive: isDragActiveB } =
    useDropzone({
      accept: { "image/*": [".png", ".jpg", ".jpeg", ".webp"] },
      maxFiles: 1,
      onDrop: (files) => {
        if (files[0] && imageA) {
          uploadMutation.mutate([files[0]]);
        }
      },
      disabled: uploadMutation.isPending || !imageA,
    });

  const handleCreateFusion = () => {
    if (imageA && imageB) {
      createFusionMutation.mutate();
    }
  };

  // Judge test mode: preload test images
  useEffect(() => {
    if (judgeTestMode && !imageA && !imageB) {
      setImageA("https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=512&h=512&fit=crop");
      setImageB("https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=512&h=512&fit=crop");
    }
  }, [judgeTestMode, imageA, imageB]);

  // Show skeleton while uploading first image (optional enhancement)
  // Uncomment if you want skeleton during initial upload:
  // if (uploadMutation.isPending && !imageA && !imageB) {
  //   return <FusionWorkspaceSkeleton />;
  // }

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <div className="mb-8">
        <h1 className="font-serif text-4xl md:text-5xl font-bold mb-4 kiro-gradient bg-clip-text text-transparent">
          Frankenstein Fusion Workspace
        </h1>
        <p className="text-muted-foreground text-lg">
          Upload two images to create a spooky fusion design
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Panel: Uploads & Options */}
        <div className="lg:col-span-3 space-y-6">
          {/* Image A Upload */}
          <Card className="kiro-glow">
            <CardHeader>
              <CardTitle className="text-sm font-medium">Base Garment (Image A)</CardTitle>
            </CardHeader>
            <CardContent>
              {imageA ? (
                <div className="relative aspect-square rounded-lg overflow-hidden border-2 border-border">
                  <img src={imageA} alt="Base garment" className="w-full h-full object-cover" loading="lazy" decoding="async" />
                  <button
                    onClick={() => setImageA(null)}
                    className="absolute top-2 right-2 bg-destructive text-destructive-foreground rounded-full p-1 hover:scale-110 transition-transform"
                    aria-label="Remove image A"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              ) : (
                <div
                  {...getRootPropsA()}
                  className={`aspect-square rounded-lg border-2 border-dashed flex flex-col items-center justify-center cursor-pointer transition-all motion-regular focus-within:outline-none focus-within:ring-2 focus-within:ring-[var(--neon-stitch)] focus-within:ring-offset-2 ${
                    isDragActiveA
                      ? "border-[var(--neon-stitch)] kiro-glow bg-[var(--neon-stitch)]/10"
                      : "border-border hover:border-primary"
                  }`}
                  role="button"
                  tabIndex={0}
                  aria-label="Upload base garment image. Drop image file or click to browse"
                  aria-describedby="upload-a-help"
                >
                  <input {...getInputPropsA()} aria-label="Base garment image file input" />
                  <Upload className="h-8 w-8 text-muted-foreground mb-2" aria-hidden="true" />
                  <p id="upload-a-help" className="text-sm text-muted-foreground text-center px-4">
                    Drop image or click to upload
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Image B Upload */}
          <Card className="kiro-glow">
            <CardHeader>
              <CardTitle className="text-sm font-medium">Pattern Source (Image B)</CardTitle>
            </CardHeader>
            <CardContent>
              {imageB ? (
                <div className="relative aspect-square rounded-lg overflow-hidden border-2 border-border">
                  <img src={imageB} alt="Pattern source" className="w-full h-full object-cover" loading="lazy" decoding="async" />
                  <button
                    onClick={() => setImageB(null)}
                    className="absolute top-2 right-2 bg-destructive text-destructive-foreground rounded-full p-1 hover:scale-110 transition-transform"
                    aria-label="Remove image B"
                  >
                    <X className="h-4 w-4" />
                  </button>
                </div>
              ) : (
                <div
                  {...getRootPropsB()}
                  className={`aspect-square rounded-lg border-2 border-dashed flex flex-col items-center justify-center cursor-pointer transition-all motion-regular ${
                    isDragActiveB
                      ? "border-[var(--neon-stitch)] kiro-glow bg-[var(--neon-stitch)]/10"
                      : "border-border hover:border-primary"
                  } ${!imageA ? "opacity-50 cursor-not-allowed" : ""}`}
                  aria-label="Upload pattern source image"
                  aria-disabled={!imageA}
                >
                  <input {...getInputPropsB()} />
                  <Upload className="h-8 w-8 text-muted-foreground mb-2" />
                  <p className="text-sm text-muted-foreground text-center px-4">
                    {imageA ? "Drop image or click to upload" : "Upload Image A first"}
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Fusion Options */}
          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <Sliders className="h-4 w-4" />
                Fusion Options
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Mode Selector */}
              <div>
                <label className="text-sm font-medium mb-2 block">Fusion Mode</label>
                <Tabs value={fusionMode} onValueChange={(v) => setFusionMode(v as any)}>
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="pattern" className="text-xs">
                      Pattern
                    </TabsTrigger>
                    <TabsTrigger value="color" className="text-xs">
                      Color
                    </TabsTrigger>
                    <TabsTrigger value="texture" className="text-xs">
                      Texture
                    </TabsTrigger>
                  </TabsList>
                </Tabs>
              </div>

              {/* Strength Slider */}
              <div>
                <label className="text-sm font-medium mb-2 block">
                  Fusion Strength: {strength[0].toFixed(1)}
                </label>
                <Slider
                  value={strength}
                  onValueChange={setStrength}
                  min={0.5}
                  max={0.9}
                  step={0.1}
                  className="w-full"
                  aria-label="Fusion strength"
                />
                <div className="flex justify-between text-xs text-muted-foreground mt-1">
                  <span>Subtle</span>
                  <span>Bold</span>
                </div>
              </div>

              {/* Create Button */}
              <Button
                onClick={handleCreateFusion}
                disabled={!imageA || !imageB || createFusionMutation.isPending}
                className="w-full kiro-glow"
                size="lg"
              >
                {createFusionMutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Create Fusion
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        </div>

        {/* Center: Output Preview */}
        <div className="lg:col-span-6 space-y-6">
          <Card className="kiro-glow">
            <CardHeader>
              <CardTitle className="text-sm font-medium">Fusion Result</CardTitle>
            </CardHeader>
            <CardContent>
              {currentJob?.status === "processing" && (
                <div className="space-y-4" role="status" aria-live="polite" aria-atomic="true">
                  <Progress value={currentJob.progress} className="h-2" aria-label={`Fusion progress: ${currentJob.progress}%`} />
                  <p className="text-sm text-muted-foreground text-center">
                    Processing fusion... {currentJob.progress}%
                  </p>
                </div>
              )}

              {currentJob?.status === "completed" && currentJob.resultUrl && (
                <div className="space-y-4">
                  <div className="relative aspect-square rounded-lg overflow-hidden border-2 border-[var(--neon-stitch)] kiro-glow">
                    <img
                      src={currentJob.resultUrl}
                      alt="Fusion result"
                      className="w-full h-full object-cover"
                      loading="lazy"
                      decoding="async"
                      onError={(e) => {
                        console.error("Failed to load fusion result image:", currentJob.resultUrl);
                        console.error("Error:", e);
                      }}
                      onLoad={() => {
                        console.log("Fusion result image loaded successfully:", currentJob.resultUrl);
                      }}
                    />
                  </div>

                  {/* Candidate Carousel */}
                  {currentJob.candidates && currentJob.candidates.length > 0 && (
                    <div className="grid grid-cols-3 gap-2">
                      {currentJob.candidates.map((url, idx) => (
                        <div
                          key={idx}
                          className="aspect-square rounded-lg overflow-hidden border border-border hover:border-[var(--neon-stitch)] transition-all cursor-pointer"
                        >
                          <img src={url} alt={`Candidate ${idx + 1}`} className="w-full h-full object-cover" loading="lazy" decoding="async" />
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Actions */}
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" className="flex-1">
                      <Download className="mr-2 h-4 w-4" />
                      Download
                    </Button>
                    <Button variant="outline" size="sm" className="flex-1">
                      <Share2 className="mr-2 h-4 w-4" />
                      Share
                    </Button>
                    <Button variant="outline" size="sm" className="flex-1">
                      <Grid3x3 className="mr-2 h-4 w-4" />
                      Lookbook
                    </Button>
                  </div>
                </div>
              )}

              {!currentJob && (
                <div className="aspect-square rounded-lg border-2 border-dashed border-border flex flex-col items-center justify-center text-muted-foreground">
                  <ImageIcon className="h-12 w-12 mb-4 opacity-50" />
                  <p className="text-sm">Upload images and create fusion to see result</p>
                </div>
              )}
              
              {/* Debug info - remove in production */}
              {currentJob && currentJob.status === "completed" && !currentJob.resultUrl && (
                <div className="p-4 bg-yellow-900/20 border border-yellow-500/50 rounded-lg">
                  <p className="text-sm text-yellow-500">
                    Status: {currentJob.status}, but no resultUrl. Job ID: {currentJob.jobId}
                  </p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Explainability Panel */}
          {currentJob?.explainability && (
            <ExplainabilityPanel explainability={currentJob.explainability} />
          )}
        </div>

        {/* Right Panel: Mannequin Try-On */}
        <div className="lg:col-span-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-medium">Try on Mannequin</CardTitle>
            </CardHeader>
            <CardContent>
              {currentJob?.status === "completed" && currentJob?.resultUrl ? (
                <MannequinCanvas 
                  imageUrl={currentJob.resultUrl} 
                  mannequinUrl="https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&h=600&fit=crop&q=80"
                />
              ) : currentJob?.status === "processing" ? (
                <div className="aspect-[3/4] rounded-lg border-2 border-dashed border-border flex flex-col items-center justify-center text-muted-foreground">
                  <Loader2 className="h-12 w-12 mb-4 opacity-50 animate-spin" />
                  <p className="text-sm">Processing fusion...</p>
                </div>
              ) : (
                <div className="aspect-[3/4] rounded-lg border-2 border-dashed border-border flex items-center justify-center text-muted-foreground">
                  <p className="text-sm text-center px-4">
                    Complete fusion to try on mannequin
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

