// AUTO-GENERATED BY KIRO
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Checkbox } from "@/components/ui/checkbox";
import type { FusionMode } from "../../../shared/schema.js";

interface FusionOptionsProps {
  mode: FusionMode;
  strength: number;
  stitchStyle?: string;
  embroideryToggle?: boolean;
  onModeChange: (mode: FusionMode) => void;
  onStrengthChange: (strength: number) => void;
  onStitchStyleChange?: (style: string) => void;
  onEmbroideryToggle?: (enabled: boolean) => void;
  faceDetected?: boolean;
  faceConsent?: boolean;
  onFaceConsentChange?: (consent: boolean) => void;
}

const STITCH_STYLES = [
  { value: "french", label: "French Seam" },
  { value: "overlock", label: "Overlock" },
  { value: "zigzag", label: "Zigzag" },
  { value: "flat", label: "Flat Felled" },
  { value: "none", label: "No Special Stitching" },
];

export function FusionOptions({
  mode,
  strength,
  stitchStyle,
  embroideryToggle,
  onModeChange,
  onStrengthChange,
  onStitchStyleChange,
  onEmbroideryToggle,
  faceDetected,
  faceConsent,
  onFaceConsentChange,
}: FusionOptionsProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Fusion Options</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Fusion Mode */}
        <div className="space-y-2">
          <Label>Fusion Mode</Label>
          <Select value={mode} onValueChange={(v) => onModeChange(v as FusionMode)}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="silhouette-first">
                Silhouette-First (preserve shape, apply patterns)
              </SelectItem>
              <SelectItem value="texture-first">
                Texture-First (prioritize fabric fidelity)
              </SelectItem>
              <SelectItem value="hybrid">Hybrid (balanced approach)</SelectItem>
            </SelectContent>
          </Select>
          <p className="text-xs text-muted-foreground">
            {mode === "silhouette-first" && "Preserves mannequin silhouette and drape"}
            {mode === "texture-first" && "Emphasizes exact fabric pattern and texture"}
            {mode === "hybrid" && "Balanced fusion of silhouette and texture"}
          </p>
        </div>

        {/* Strength */}
        <div className="space-y-2">
          <Label>Fusion Strength: {strength.toFixed(2)}</Label>
          <Slider
            value={[strength]}
            onValueChange={([v]) => onStrengthChange(v)}
            min={0.35}
            max={0.7}
            step={0.05}
          />
          <p className="text-xs text-muted-foreground">
            Controls how much the fabric images influence the final result
          </p>
        </div>

        {/* Stitch Style */}
        {onStitchStyleChange && (
          <div className="space-y-2">
            <Label>Stitch Style</Label>
            <Select value={stitchStyle || "none"} onValueChange={onStitchStyleChange}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {STITCH_STYLES.map((style) => (
                  <SelectItem key={style.value} value={style.value}>
                    {style.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}

        {/* Embroidery Toggle */}
        {onEmbroideryToggle && (
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label>Embroidery Effects</Label>
              <p className="text-xs text-muted-foreground">
                Add decorative embroidery patterns
              </p>
            </div>
            <Switch
              checked={embroideryToggle || false}
              onCheckedChange={onEmbroideryToggle}
            />
          </div>
        )}

        {/* Face Consent (if faces detected) */}
        {faceDetected && onFaceConsentChange && (
          <Alert className="border-amber-500 bg-amber-50 dark:bg-amber-950/20">
            <AlertDescription>
              <div className="space-y-2">
                <p className="font-medium">⚠️ Faces Detected</p>
                <p className="text-sm">
                  Faces were detected in your uploaded images. To protect privacy, faces will be automatically masked during processing.
                </p>
                <div className="flex items-center space-x-2 pt-2">
                  <Checkbox
                    id="face-consent"
                    checked={faceConsent || false}
                    onCheckedChange={(checked) => onFaceConsentChange(checked === true)}
                  />
                  <Label htmlFor="face-consent" className="text-sm cursor-pointer font-normal">
                    I consent to face masking for privacy protection
                  </Label>
                </div>
                {!faceConsent && (
                  <p className="text-xs text-amber-700 dark:text-amber-400 mt-1">
                    You must provide consent to proceed with images containing faces.
                  </p>
                )}
              </div>
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
    </Card>
  );
}

