// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Download, Share2, Heart, RotateCw } from "lucide-react";
import type { FusionJob } from "../../../shared/schema.js";
import { ExplainabilityPanel } from "./ExplainabilityPanel";

interface FusionResultsProps {
  job: FusionJob;
  onRegenerate?: () => void;
  onSaveLookbook?: () => void;
  onShare?: () => void;
}

export function FusionResults({
  job,
  onRegenerate,
  onSaveLookbook,
  onShare,
}: FusionResultsProps) {
  const [selectedCandidate, setSelectedCandidate] = useState(0);

  if (!job.resultUrl && (!job.candidates || job.candidates.length === 0)) {
    return null;
  }

  const displayUrl = job.resultUrl || job.candidates?.[selectedCandidate]?.url;

  return (
    <Card>
      <CardHeader>
        <CardTitle>Fusion Results</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Tabs defaultValue="result" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="result">Result</TabsTrigger>
            <TabsTrigger value="candidates">Candidates ({job.candidates?.length || 0})</TabsTrigger>
            <TabsTrigger value="explainability">Explainability</TabsTrigger>
          </TabsList>

          <TabsContent value="result" className="space-y-4">
            <div className="relative">
              <img
                src={displayUrl}
                alt="Fusion result"
                className="w-full rounded-lg"
              />
            </div>

            <div className="flex flex-wrap gap-2">
              <Button onClick={onRegenerate} variant="outline">
                <RotateCw className="h-4 w-4 mr-2" />
                Regenerate
              </Button>
              <Button onClick={onSaveLookbook} variant="outline">
                <Heart className="h-4 w-4 mr-2" />
                Save to Lookbook
              </Button>
              <Button onClick={onShare} variant="outline">
                <Share2 className="h-4 w-4 mr-2" />
                Share
              </Button>
              <Button
                variant="outline"
                onClick={() => {
                  const link = document.createElement("a");
                  link.href = displayUrl || "";
                  link.download = `fusion-${job.jobId}.jpg`;
                  link.click();
                }}
              >
                <Download className="h-4 w-4 mr-2" />
                Download
              </Button>
            </div>
          </TabsContent>

          <TabsContent value="candidates" className="space-y-4">
            {job.candidates && job.candidates.length > 0 ? (
              <div className="grid grid-cols-3 gap-4">
                {job.candidates?.map((candidate: { url: string; mode: string; thumbnail?: string }, idx: number) => (
                  <Card
                    key={idx}
                    className={`cursor-pointer transition-all ${
                      selectedCandidate === idx
                        ? "border-2 border-primary"
                        : "border hover:border-primary/50"
                    }`}
                    onClick={() => setSelectedCandidate(idx)}
                  >
                    <CardContent className="p-2">
                      <img
                        src={candidate.thumbnail || candidate.url}
                        alt={`Candidate ${idx + 1} - ${candidate.mode}`}
                        className="w-full h-48 object-cover rounded"
                      />
                      <p className="text-xs text-center mt-2 text-muted-foreground">
                        {candidate.mode}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : (
              <p className="text-muted-foreground">No candidates available</p>
            )}
          </TabsContent>

          <TabsContent value="explainability">
            {job.explainability ? (
              <ExplainabilityPanel explainability={job.explainability} />
            ) : (
              <p className="text-muted-foreground">Explainability data not available</p>
            )}
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}

