// AUTO-GENERATED BY KIRO
import { useState, useEffect, useRef } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { ChevronLeft, ChevronRight, Sparkles, ArrowRight } from "lucide-react";
import { motion, useScroll, useTransform, AnimatePresence } from "framer-motion";

interface BeforeAfterPair {
  before: string;
  after: string;
  title: string;
  description: string;
}

interface HeroProps {
  beforeAfterPairs?: BeforeAfterPair[];
  headline?: string;
  subheadline?: string;
  ctaText?: string;
  ctaLink?: string;
}

// Better sample data with actual fashion images
const defaultPairs: BeforeAfterPair[] = [
  {
    before: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&h=1000&fit=crop&q=80",
    after: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop&q=80",
    title: "Classic Meets Gothic",
    description: "Traditional elegance fused with Victorian patterns",
  },
  {
    before: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800&h=1000&fit=crop&q=80",
    after: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop&q=80",
    title: "Pattern Fusion",
    description: "Simple designs enhanced with intricate motifs",
  },
  {
    before: "https://images.unsplash.com/photo-1566479179817-4d448f472137?w=800&h=1000&fit=crop&q=80",
    after: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&h=1000&fit=crop&q=80",
    title: "Spooky Elegance",
    description: "Everyday wear transformed with gothic accents",
  },
];

export function Hero({
  beforeAfterPairs = defaultPairs,
  headline = "Stitch the Impossible",
  subheadline = "Create couture fusions in seconds with AI-powered design",
  ctaText = "Try FrankenStitch",
  ctaLink = "/fusion",
}: HeroProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isAutoplay, setIsAutoplay] = useState(true);
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end start"],
  });

  const opacity = useTransform(scrollYProgress, [0, 0.5], [1, 0]);
  const y = useTransform(scrollYProgress, [0, 0.5], [0, -50]);

  // Autoplay carousel
  useEffect(() => {
    if (!isAutoplay) return;
    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % beforeAfterPairs.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [isAutoplay, beforeAfterPairs.length]);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % beforeAfterPairs.length);
    setIsAutoplay(false);
    setTimeout(() => setIsAutoplay(true), 10000);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + beforeAfterPairs.length) % beforeAfterPairs.length);
    setIsAutoplay(false);
    setTimeout(() => setIsAutoplay(true), 10000);
  };

  const currentPair = beforeAfterPairs[currentIndex];

  return (
    <motion.section
      ref={containerRef}
      style={{ opacity, y }}
      className="relative min-h-screen flex items-center justify-center overflow-hidden bg-gradient-to-br from-background via-background to-primary/5"
      aria-label="Hero section with before and after fashion fusion examples"
    >
      {/* Subtle background pattern */}
      <div className="absolute inset-0 opacity-[0.02]">
        <div className="absolute inset-0" style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
        }} />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left: Text Content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="space-y-8"
          >
            <div className="space-y-4">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20"
              >
                <Sparkles className="h-4 w-4 text-primary" />
                <span className="text-sm font-medium text-primary">AI-Powered Design</span>
              </motion.div>
              
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="font-serif text-5xl md:text-6xl lg:text-7xl font-bold leading-tight"
              >
                <span className="bg-gradient-to-r from-foreground via-foreground to-foreground/70 bg-clip-text text-transparent">
                  {headline}
                </span>
              </motion.h1>
              
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.3 }}
                className="text-lg md:text-xl text-muted-foreground leading-relaxed max-w-xl"
              >
                {subheadline}
              </motion.p>
            </div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
              className="flex flex-col sm:flex-row gap-4"
            >
              <Link href={ctaLink}>
                <Button
                  size="lg"
                  className="text-base px-8 py-6 h-auto group"
                  aria-label={ctaText}
                >
                  {ctaText}
                  <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Link href="/#gallery">
                <Button
                  size="lg"
                  variant="outline"
                  className="text-base px-8 py-6 h-auto"
                >
                  View Gallery
                </Button>
              </Link>
            </motion.div>

            {/* Stats */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="grid grid-cols-3 gap-6 pt-8 border-t border-border"
            >
              <div>
                <div className="text-2xl font-bold">1000+</div>
                <div className="text-sm text-muted-foreground">Fusions Created</div>
              </div>
              <div>
                <div className="text-2xl font-bold">AI</div>
                <div className="text-sm text-muted-foreground">Powered</div>
              </div>
              <div>
                <div className="text-2xl font-bold">5s</div>
                <div className="text-sm text-muted-foreground">Avg. Time</div>
              </div>
            </motion.div>
          </motion.div>

          {/* Right: Before/After Carousel */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="relative"
          >
            <div className="relative bg-card rounded-2xl border border-border/50 p-6 shadow-2xl">
              {/* Carousel Controls */}
              <button
                onClick={prevSlide}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    prevSlide();
                  }
                }}
                className="absolute left-4 top-1/2 -translate-y-1/2 z-20 bg-background/95 hover:bg-background rounded-full p-3 border border-border shadow-lg transition-all focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                aria-label="Previous transformation"
              >
                <ChevronLeft className="h-5 w-5" />
              </button>
              <button
                onClick={nextSlide}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    nextSlide();
                  }
                }}
                className="absolute right-4 top-1/2 -translate-y-1/2 z-20 bg-background/95 hover:bg-background rounded-full p-3 border border-border shadow-lg transition-all focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                aria-label="Next transformation"
              >
                <ChevronRight className="h-5 w-5" />
              </button>

              {/* Before/After Comparison */}
              <div className="grid grid-cols-2 gap-4">
                {/* Before */}
                <AnimatePresence mode="wait">
                  <motion.div
                    key={`before-${currentIndex}`}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.4 }}
                    className="space-y-2"
                  >
                    <div className="flex items-center gap-2">
                      <div className="h-0.5 w-8 bg-muted-foreground/40 rounded" />
                      <span className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                        Before
                      </span>
                    </div>
                    <div className="relative aspect-[3/4] rounded-lg overflow-hidden border border-border/50 bg-muted">
                      <img
                        src={currentPair.before}
                        alt={`Before: ${currentPair.title}`}
                        className="w-full h-full object-cover"
                        loading="eager"
                      />
                    </div>
                  </motion.div>
                </AnimatePresence>

                {/* After */}
                <AnimatePresence mode="wait">
                  <motion.div
                    key={`after-${currentIndex}`}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.4 }}
                    className="space-y-2"
                  >
                    <div className="flex items-center gap-2">
                      <div className="h-0.5 w-8 bg-primary rounded" />
                      <span className="text-xs font-medium text-primary uppercase tracking-wider">
                        After
                      </span>
                    </div>
                    <div className="relative aspect-[3/4] rounded-lg overflow-hidden border-2 border-primary/50 shadow-lg">
                      <img
                        src={currentPair.after}
                        alt={`After: ${currentPair.title}`}
                        className="w-full h-full object-cover"
                        loading="eager"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-primary/10 to-transparent pointer-events-none" />
                    </div>
                  </motion.div>
                </AnimatePresence>
              </div>

              {/* Carousel Info */}
              <div className="mt-6 text-center space-y-3">
                <h3 className="font-serif text-xl font-semibold">
                  {currentPair.title}
                </h3>
                <p className="text-sm text-muted-foreground">{currentPair.description}</p>
                
                {/* Dots indicator */}
                <div className="flex justify-center gap-2 mt-4">
                  {beforeAfterPairs.map((_, idx) => (
                    <button
                      key={idx}
                      onClick={() => {
                        setCurrentIndex(idx);
                        setIsAutoplay(false);
                        setTimeout(() => setIsAutoplay(true), 10000);
                      }}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" || e.key === " ") {
                          e.preventDefault();
                          setCurrentIndex(idx);
                          setIsAutoplay(false);
                          setTimeout(() => setIsAutoplay(true), 10000);
                        }
                      }}
                      className={`h-2 rounded-full transition-all ${
                        idx === currentIndex
                          ? "w-8 bg-primary"
                          : "w-2 bg-muted-foreground/30 hover:bg-muted-foreground/50"
                      }`}
                      aria-label={`Go to slide ${idx + 1} of ${beforeAfterPairs.length}`}
                      aria-current={idx === currentIndex ? "true" : "false"}
                    />
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Scroll indicator */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1 }}
        className="absolute bottom-8 left-1/2 -translate-x-1/2"
      >
        <motion.div
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
          className="flex flex-col items-center gap-2 text-muted-foreground"
        >
          <span className="text-xs uppercase tracking-wider">Scroll</span>
          <ChevronLeft className="h-4 w-4 rotate-90" />
        </motion.div>
      </motion.div>
    </motion.section>
  );
}
