// AUTO-GENERATED BY KIRO
import { useState, useEffect, useRef } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { ChevronLeft, ChevronRight, Sparkles } from "lucide-react";
import { motion, useScroll, useTransform } from "framer-motion";

interface BeforeAfterPair {
  before: string;
  after: string;
  title: string;
  description: string;
}

interface HeroProps {
  beforeAfterPairs?: BeforeAfterPair[];
  headline?: string;
  subheadline?: string;
  ctaText?: string;
  ctaLink?: string;
}

// Sample data for demo
const defaultPairs: BeforeAfterPair[] = [
  {
    before: "/api/placeholder/800/600?text=Traditional+Saree",
    after: "/api/placeholder/800/600?text=Fused+Design",
    title: "Classic Meets Gothic",
    description: "Traditional red saree fused with Victorian patterns",
  },
  {
    before: "/api/placeholder/800/600?text=Plain+Lehenga",
    after: "/api/placeholder/800/600?text=Embroidered+Fusion",
    title: "Pattern Fusion",
    description: "Simple lehenga enhanced with intricate paisley motifs",
  },
  {
    before: "/api/placeholder/800/600?text=Basic+Salwar",
    after: "/api/placeholder/800/600?text=Kiroween+Style",
    title: "Spooky Elegance",
    description: "Everyday wear transformed with gothic accents",
  },
];

export function Hero({
  beforeAfterPairs = defaultPairs,
  headline = "Stitch the Impossible — Create couture fusions in seconds.",
  subheadline = "Frankenstein Fusion Outfit Designer: Where traditional meets gothic, powered by AI.",
  ctaText = "Try FrankenStitch",
  ctaLink = "/fusion",
}: HeroProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isAutoplay, setIsAutoplay] = useState(true);
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end start"],
  });

  const opacity = useTransform(scrollYProgress, [0, 0.5], [1, 0]);
  const y = useTransform(scrollYProgress, [0, 0.5], [0, -100]);

  // Autoplay carousel
  useEffect(() => {
    if (!isAutoplay) return;
    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % beforeAfterPairs.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [isAutoplay, beforeAfterPairs.length]);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % beforeAfterPairs.length);
    setIsAutoplay(false);
    setTimeout(() => setIsAutoplay(true), 10000);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + beforeAfterPairs.length) % beforeAfterPairs.length);
    setIsAutoplay(false);
    setTimeout(() => setIsAutoplay(true), 10000);
  };

  const currentPair = beforeAfterPairs[currentIndex];

  return (
    <motion.section
      ref={containerRef}
      style={{ opacity, y }}
      className="relative h-[85vh] min-h-[600px] flex items-center justify-center overflow-hidden kiro-fog kiro-vignette"
      aria-label="Hero section with before and after fashion fusion examples"
    >
      {/* Background gradient with fog */}
      <div className="absolute inset-0 kiro-gradient opacity-20" />
      <div className="absolute inset-0 bg-[var(--bg-900)]" />
      
      {/* Animated fog overlay */}
      <div className="absolute inset-0 kiro-fog pointer-events-none" />

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
        {/* Headline */}
        <div className="text-center mb-12">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="font-serif text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6 bg-gradient-to-r from-[var(--accent-gradient-start)] to-[var(--accent-gradient-end)] bg-clip-text text-transparent"
          >
            {headline}
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto mb-8"
          >
            {subheadline}
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            <Link href={ctaLink}>
              <Button
                size="lg"
                className="text-base kiro-glow hover:scale-105 transition-transform motion-regular"
                aria-label={ctaText}
              >
                <Sparkles className="mr-2 h-5 w-5" />
                {ctaText}
              </Button>
            </Link>
          </motion.div>
        </div>

        {/* Before/After Carousel */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8, delay: 0.6 }}
          className="max-w-6xl mx-auto"
        >
          <div className="relative bg-card/50 backdrop-blur-sm rounded-lg border border-border/50 p-6 md:p-8 kiro-glow">
            {/* Carousel Controls */}
            <button
              onClick={prevSlide}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  prevSlide();
                }
              }}
              className="absolute left-4 top-1/2 -translate-y-1/2 z-20 bg-background/80 hover:bg-background rounded-full p-2 border border-border kiro-glow transition-all motion-fast focus:outline-none focus:ring-2 focus:ring-[var(--neon-stitch)] focus:ring-offset-2"
              aria-label="Previous transformation"
              aria-controls="hero-carousel"
            >
              <ChevronLeft className="h-6 w-6" />
            </button>
            <button
              onClick={nextSlide}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  nextSlide();
                }
              }}
              className="absolute right-4 top-1/2 -translate-y-1/2 z-20 bg-background/80 hover:bg-background rounded-full p-2 border border-border kiro-glow transition-all motion-fast focus:outline-none focus:ring-2 focus:ring-[var(--neon-stitch)] focus:ring-offset-2"
              aria-label="Next transformation"
              aria-controls="hero-carousel"
            >
              <ChevronRight className="h-6 w-6" />
            </button>

        {/* Before/After Comparison */}
        <div id="hero-carousel" className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8" role="region" aria-label="Fashion transformation examples">
              {/* Before */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="h-1 w-12 bg-muted-foreground/30 rounded" />
                  <span className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
                    Before
                  </span>
                </div>
                <div className="relative aspect-[4/5] rounded-lg overflow-hidden border-2 border-border/50 kiro-vignette">
                  <img
                    src={currentPair.before}
                    alt={`Before: ${currentPair.title}`}
                    className="w-full h-full object-cover"
                    loading="eager"
                  />
                </div>
              </div>

              {/* Arrow */}
              <div className="hidden md:flex items-center justify-center">
                <motion.div
                  animate={{ x: [0, 10, 0] }}
                  transition={{ duration: 2, repeat: Infinity }}
                  className="text-[var(--neon-stitch)]"
                >
                  <svg
                    className="h-12 w-12"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M13 7l5 5m0 0l-5 5m5-5H6"
                    />
                  </svg>
                </motion.div>
              </div>

              {/* After */}
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <div className="h-1 w-12 bg-[var(--neon-stitch)] rounded kiro-glow" />
                  <span className="text-sm font-medium text-[var(--neon-stitch)] uppercase tracking-wider">
                    After
                  </span>
                </div>
                <motion.div
                  key={currentIndex}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.5 }}
                  className="relative aspect-[4/5] rounded-lg overflow-hidden border-2 border-[var(--neon-stitch)]/50 kiro-glow kiro-vignette"
                >
                  <img
                    src={currentPair.after}
                    alt={`After: ${currentPair.title}`}
                    className="w-full h-full object-cover"
                    loading="eager"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-[var(--bg-900)]/60 to-transparent" />
                </motion.div>
              </div>
            </div>

            {/* Carousel Info */}
            <div className="mt-6 text-center">
              <h3 className="font-serif text-xl md:text-2xl font-semibold mb-2">
                {currentPair.title}
              </h3>
              <p className="text-sm text-muted-foreground">{currentPair.description}</p>
              
              {/* Dots indicator */}
              <div className="flex justify-center gap-2 mt-4">
                {beforeAfterPairs.map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setCurrentIndex(idx);
                      setIsAutoplay(false);
                      setTimeout(() => setIsAutoplay(true), 10000);
                    }}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" || e.key === " ") {
                        e.preventDefault();
                        setCurrentIndex(idx);
                        setIsAutoplay(false);
                        setTimeout(() => setIsAutoplay(true), 10000);
                      }
                    }}
                    className={`h-2 rounded-full transition-all motion-fast focus:outline-none focus:ring-2 focus:ring-[var(--neon-stitch)] focus:ring-offset-2 ${
                      idx === currentIndex
                        ? "w-8 bg-[var(--neon-stitch)] kiro-glow"
                        : "w-2 bg-muted-foreground/30"
                    }`}
                    aria-label={`Go to slide ${idx + 1} of ${beforeAfterPairs.length}`}
                    aria-current={idx === currentIndex ? "true" : "false"}
                    role="tab"
                  />
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Scroll indicator */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce">
        <ChevronLeft className="h-6 w-6 text-muted-foreground rotate-90" />
      </div>
    </motion.section>
  );
}

