// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { Link } from "wouter";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  FolderOpen,
  Code,
  FileText,
  Sparkles,
  ExternalLink,
  Copy,
  CheckCircle2,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface JudgeTestModeProps {
  enabled: boolean;
  onToggle: (enabled: boolean) => void;
}

export function JudgeTestMode({ enabled, onToggle }: JudgeTestModeProps) {
  const { toast } = useToast();
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    toast({ title: `Copied ${label} to clipboard` });
    setTimeout(() => setCopied(null), 2000);
  };

  const kiroPrompts = [
    {
      label: "Design System Prompt",
      prompt: `Create a Kiroween dark theme for a fashion design app. Include design tokens: primary dark background #0b0f12, secondary #0f1720, accent gradient from #ff6b6b to #9b59ff, neon stitch #ff8fb1, fog overlay rgba(20,16,30,0.45). Add Tailwind config extensions for colors, spacing, shadows, and motion tokens.`,
    },
    {
      label: "Fusion Workspace Prompt",
      prompt: `Build a FusionWorkspace React component with: left panel for two image uploads (drag-and-drop), center panel for fusion result preview, right panel for mannequin try-on, fusion mode selector, strength slider, create fusion button, progress bar, explainability panel integration. Use TypeScript, Tailwind, shadcn/ui components.`,
    },
    {
      label: "Backend Endpoints Prompt",
      prompt: `Create Express/TypeScript endpoints for fusion: POST /api/fusion/upload (multer, validate images, upload to Cloudinary), POST /api/fusion/create (create fusion job), GET /api/fusion/status/:jobId (poll job status), GET /api/fusion/results/:jobId (return results with explainability). Include error handling and validation.`,
    },
  ];

  if (!enabled) return null;

  return (
    <div className="space-y-4 mb-6">
      <Card className="border-[var(--neon-stitch)]/50 kiro-glow">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-[var(--neon-stitch)]" />
            Judge Test Mode - Kiro Integration Showcase
          </CardTitle>
          <CardDescription>
            This panel highlights how Kiro (AI pair programmer) was used to build this system
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="kiro-folder" className="w-full">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="kiro-folder">.kiro Folder</TabsTrigger>
              <TabsTrigger value="prompts">Kiro Prompts</TabsTrigger>
              <TabsTrigger value="test-data">Test Data</TabsTrigger>
            </TabsList>

            <TabsContent value="kiro-folder" className="space-y-4">
              <div className="space-y-2">
                <h3 className="font-semibold text-sm flex items-center gap-2">
                  <FolderOpen className="h-4 w-4" />
                  Kiro Artifacts
                </h3>
                <p className="text-sm text-muted-foreground">
                  The `.kiro` folder contains specifications, steering documents, and hooks that guided code generation.
                </p>
              </div>

              <div className="grid gap-2">
                <div className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm font-mono">.kiro/spec.yaml</span>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Module Specs
                  </Badge>
                </div>

                <div className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm font-mono">.kiro/steering.md</span>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Design Constraints
                  </Badge>
                </div>

                <div className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm font-mono">.kiro/hooks/onUpload.hook.yaml</span>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    Event Hook
                  </Badge>
                </div>

                <div className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm font-mono">.kiro/prompts/fusion_prompt_templates.md</span>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    AI Templates
                  </Badge>
                </div>
              </div>

              <div className="pt-2 border-t border-border">
                <Link href="/fusion">
                  <Button variant="outline" size="sm" className="w-full">
                    <ExternalLink className="mr-2 h-4 w-4" />
                    View Fusion Workspace
                  </Button>
                </Link>
              </div>
            </TabsContent>

            <TabsContent value="prompts" className="space-y-4">
              <div className="space-y-2">
                <h3 className="font-semibold text-sm flex items-center gap-2">
                  <Code className="h-4 w-4" />
                  Example Kiro Prompts
                </h3>
                <p className="text-sm text-muted-foreground">
                  These are the exact prompts used to generate core components and features.
                </p>
              </div>

              <div className="space-y-3">
                {kiroPrompts.map((item, idx) => (
                  <Card key={idx} className="border-border">
                    <CardHeader className="pb-3">
                      <div className="flex items-center justify-between">
                        <CardTitle className="text-sm">{item.label}</CardTitle>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => copyToClipboard(item.prompt, item.label)}
                          className="h-8 w-8 p-0"
                          aria-label={`Copy ${item.label} prompt`}
                        >
                          {copied === item.label ? (
                            <CheckCircle2 className="h-4 w-4 text-green-500" />
                          ) : (
                            <Copy className="h-4 w-4" />
                          )}
                        </Button>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <pre className="text-xs bg-muted p-3 rounded-lg overflow-x-auto font-mono">
                        {item.prompt}
                      </pre>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </TabsContent>

            <TabsContent value="test-data" className="space-y-4">
              <div className="space-y-2">
                <h3 className="font-semibold text-sm">Test Images</h3>
                <p className="text-sm text-muted-foreground">
                  Preloaded test images for quick demo. Click "Create Fusion" to see the pipeline in action.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <Card className="border-border">
                  <CardHeader className="pb-2">
                    <CardTitle className="text-xs">Image A (Base)</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="aspect-square bg-muted rounded-lg flex items-center justify-center">
                      <span className="text-xs text-muted-foreground">Traditional Saree</span>
                    </div>
                  </CardContent>
                </Card>

                <Card className="border-border">
                  <CardHeader className="pb-2">
                    <CardTitle className="text-xs">Image B (Pattern)</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="aspect-square bg-muted rounded-lg flex items-center justify-center">
                      <span className="text-xs text-muted-foreground">Victorian Pattern</span>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <div className="pt-2 border-t border-border">
                <p className="text-xs text-muted-foreground mb-2">
                  Test images are automatically loaded when Judge Test Mode is enabled.
                </p>
                <Badge variant="secondary" className="text-xs">
                  Auto-loaded in Fusion Workspace
                </Badge>
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
}

