// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Grid3x3, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api";

interface LookbookGeneratorProps {
  jobId: string;
  baseImageUrl: string;
}

export function LookbookGenerator({ jobId, baseImageUrl }: LookbookGeneratorProps) {
  const [lookbookUrls, setLookbookUrls] = useState<string[]>([]);

  const generateLookbookMutation = useMutation({
    mutationFn: async () => {
      const response = await api.post("/api/fusion/lookbook", {
        jobId,
        baseImageUrl,
        count: 6,
      });
      return response.data;
    },
    onSuccess: (data) => {
      setLookbookUrls(data.variations);
    },
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm font-medium flex items-center gap-2">
          <Grid3x3 className="h-4 w-4" />
          Lookbook Generator
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Button
          onClick={() => generateLookbookMutation.mutate()}
          disabled={generateLookbookMutation.isPending}
          className="w-full"
          variant="outline"
        >
          {generateLookbookMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Grid3x3 className="mr-2 h-4 w-4" />
              Generate 6 Variations
            </>
          )}
        </Button>

        {lookbookUrls.length > 0 && (
          <div className="grid grid-cols-3 gap-2">
            {lookbookUrls.map((url, idx) => (
              <div
                key={idx}
                className="aspect-square rounded-lg overflow-hidden border border-border hover:border-[var(--neon-stitch)] transition-all cursor-pointer"
              >
                <img src={url} alt={`Lookbook variation ${idx + 1}`} className="w-full h-full object-cover" loading="lazy" decoding="async" />
              </div>
            ))}
          </div>
        )}

        {lookbookUrls.length > 0 && (
          <Button variant="outline" size="sm" className="w-full">
            <Download className="mr-2 h-4 w-4" />
            Download All
          </Button>
        )}
      </CardContent>
    </Card>
  );
}

