// AUTO-GENERATED BY KIRO
import { useState, useRef, useEffect } from "react";
import { Move, ZoomIn, ZoomOut, RotateCw, Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";

interface MannequinCanvasProps {
  imageUrl: string;
  mannequinUrl?: string;
}

export function MannequinCanvas({
  imageUrl,
  mannequinUrl = "/api/placeholder/400/600?text=Mannequin",
}: MannequinCanvasProps) {
  const [scale, setScale] = useState([1]);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [rotation, setRotation] = useState(0);
  const [showOverlay, setShowOverlay] = useState(true);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const canvasRef = useRef<HTMLDivElement>(null);

  const handleMouseDown = (e: React.MouseEvent) => {
    setIsDragging(true);
    setDragStart({
      x: e.clientX - position.x,
      y: e.clientY - position.y,
    });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging) {
      setPosition({
        x: e.clientX - dragStart.x,
        y: e.clientY - dragStart.y,
      });
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  const resetTransform = () => {
    setScale([1]);
    setPosition({ x: 0, y: 0 });
    setRotation(0);
  };

  return (
    <div className="space-y-4">
      {/* Controls */}
      <div className="flex flex-wrap gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => setScale([Math.min(scale[0] + 0.1, 2)])}
          aria-label="Zoom in"
        >
          <ZoomIn className="h-4 w-4" />
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setScale([Math.max(scale[0] - 0.1, 0.5)])}
          aria-label="Zoom out"
        >
          <ZoomOut className="h-4 w-4" />
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setRotation((prev) => (prev + 90) % 360)}
          aria-label="Rotate"
        >
          <RotateCw className="h-4 w-4" />
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => setShowOverlay(!showOverlay)}
          aria-label="Toggle overlay"
        >
          {showOverlay ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
        </Button>
        <Button variant="outline" size="sm" onClick={resetTransform}>
          Reset
        </Button>
      </div>

      {/* Canvas */}
      <div
        ref={canvasRef}
        className="relative aspect-[3/4] rounded-lg overflow-hidden border-2 border-border bg-muted"
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{ cursor: isDragging ? "grabbing" : "grab" }}
      >
        {/* Mannequin Background */}
        <img
          src={mannequinUrl}
          alt="Mannequin"
          className="absolute inset-0 w-full h-full object-cover opacity-30"
          loading="lazy"
          decoding="async"
        />

        {/* Fusion Image Overlay */}
        <div
          className="absolute inset-0 flex items-center justify-center"
          style={{
            transform: `translate(${position.x}px, ${position.y}px) scale(${scale[0]}) rotate(${rotation}deg)`,
            transition: isDragging ? "none" : "transform 0.2s ease-out",
          }}
        >
          <img
            src={imageUrl}
            alt="Fusion design on mannequin"
            className="max-w-full max-h-full object-contain"
            draggable={false}
            loading="lazy"
            decoding="async"
          />
        </div>

        {/* Spooky Overlay Toggle */}
        {showOverlay && (
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[var(--fog-overlay)] to-[var(--bg-900)]/80 pointer-events-none" />
        )}

        {/* Drag Indicator */}
        {isDragging && (
          <div className="absolute top-2 left-2 bg-background/80 rounded px-2 py-1 text-xs flex items-center gap-1">
            <Move className="h-3 w-3" />
            Dragging
          </div>
        )}
      </div>

      {/* Scale Slider */}
      <div>
        <label className="text-xs text-muted-foreground mb-1 block">
          Scale: {(scale[0] * 100).toFixed(0)}%
        </label>
        <Slider
          value={scale}
          onValueChange={setScale}
          min={0.5}
          max={2}
          step={0.1}
          className="w-full"
          aria-label="Image scale"
        />
      </div>
    </div>
  );
}

