// AUTO-GENERATED BY KIRO
import { cn } from "@/lib/utils";

interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {}

export function Skeleton({ className, ...props }: SkeletonProps) {
  return (
    <div
      className={cn("animate-pulse rounded-md bg-muted", className)}
      {...props}
    />
  );
}

export function CardSkeleton() {
  return (
    <div className="rounded-lg border border-border p-6 space-y-4">
      <Skeleton className="h-4 w-1/4" />
      <Skeleton className="h-8 w-1/2" />
      <Skeleton className="h-4 w-3/4" />
    </div>
  );
}

export function ImageSkeleton({ aspectRatio = "aspect-square" }: { aspectRatio?: string }) {
  return (
    <div className={cn("rounded-lg overflow-hidden bg-muted", aspectRatio)}>
      <Skeleton className="h-full w-full" />
    </div>
  );
}

export function FusionWorkspaceSkeleton() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <div className="mb-8 space-y-4">
        <Skeleton className="h-10 w-64" />
        <Skeleton className="h-6 w-96" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Panel */}
        <div className="lg:col-span-3 space-y-6">
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
        </div>

        {/* Center Panel */}
        <div className="lg:col-span-6 space-y-6">
          <CardSkeleton />
          <CardSkeleton />
        </div>

        {/* Right Panel */}
        <div className="lg:col-span-3">
          <CardSkeleton />
        </div>
      </div>
    </div>
  );
}

