// AUTO-GENERATED BY KIRO
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Share2, Download, Loader2, Instagram } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api } from "@/lib/api";

interface SocialShareCardProps {
  jobId: string;
  resultUrl: string;
}

export function SocialShareCard({ jobId, resultUrl }: SocialShareCardProps) {
  const [shareCardUrl, setShareCardUrl] = useState<string | null>(null);

  const generateShareCardMutation = useMutation({
    mutationFn: async () => {
      const response = await api.post("/api/fusion/share-card", {
        jobId,
        resultUrl,
        dimensions: { width: 1080, height: 1080 },
      });
      return response.data;
    },
    onSuccess: (data) => {
      setShareCardUrl(data.shareCardUrl);
    },
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm font-medium flex items-center gap-2">
          <Share2 className="h-4 w-4" />
          Social Share Card
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Button
          onClick={() => generateShareCardMutation.mutate()}
          disabled={generateShareCardMutation.isPending}
          className="w-full"
          variant="outline"
        >
          {generateShareCardMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Instagram className="mr-2 h-4 w-4" />
              Generate Instagram Card
            </>
          )}
        </Button>

        {shareCardUrl && (
          <>
            <div className="aspect-square rounded-lg overflow-hidden border-2 border-border">
              <img src={shareCardUrl} alt="Social share card" className="w-full h-full object-cover" loading="lazy" decoding="async" />
            </div>
            <Button variant="outline" size="sm" className="w-full">
              <Download className="mr-2 h-4 w-4" />
              Download (1080x1080)
            </Button>
          </>
        )}
      </CardContent>
    </Card>
  );
}

