// AUTO-GENERATED BY KIRO
import { useState, useRef, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { RotateCw, ZoomIn, ZoomOut, Move } from "lucide-react";

interface TryOnCanvasProps {
  resultUrl?: string;
  mannequinUrl?: string;
}

export function TryOnCanvas({ resultUrl, mannequinUrl }: TryOnCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [scale, setScale] = useState(1);
  const [rotation, setRotation] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || !resultUrl) return;

    const ctx = canvas.getContext("2d");
    if (!ctx || !canvas) return;

    // Set canvas size
    canvas.width = 800;
    canvas.height = 1000;

    // Load images
    const mannequinImg = new Image();
    const resultImg = new Image();

    mannequinImg.crossOrigin = "anonymous";
    resultImg.crossOrigin = "anonymous";

    mannequinImg.onload = () => {
      // Draw mannequin (30% opacity)
      ctx.globalAlpha = 0.3;
      ctx.drawImage(mannequinImg, 0, 0, canvas.width, canvas.height);
      ctx.globalAlpha = 1.0;

      // Draw result image with transformations
      if (resultImg.complete) {
        drawResult(ctx, resultImg);
      }
    };

    resultImg.onload = () => {
      drawResult(ctx, resultImg);
    };

    if (mannequinUrl) {
      mannequinImg.src = mannequinUrl;
    } else {
      // Use default mannequin silhouette
      ctx.fillStyle = "#f0f0f0";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    }

    resultImg.src = resultUrl;

    function drawResult(ctx: CanvasRenderingContext2D, img: HTMLImageElement) {
      if (!canvas) return;
      ctx.save();
      ctx.translate(canvas.width / 2 + position.x, canvas.height / 2 + position.y);
      ctx.rotate((rotation * Math.PI) / 180);
      ctx.scale(scale, scale);
      ctx.drawImage(img, -img.width / 2, -img.height / 2);
      ctx.restore();
    }
  }, [resultUrl, mannequinUrl, position, scale, rotation]);

  const handleMouseDown = (e: React.MouseEvent) => {
    setIsDragging(true);
    setDragStart({ x: e.clientX - position.x, y: e.clientY - position.y });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging) {
      setPosition({
        x: e.clientX - dragStart.x,
        y: e.clientY - dragStart.y,
      });
    }
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  if (!resultUrl) {
    return (
      <Card>
        <CardContent className="p-8 text-center text-muted-foreground">
          No result available for try-on
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Try-On Canvas</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="relative border rounded-lg overflow-hidden bg-muted">
          <canvas
            ref={canvasRef}
            className="w-full cursor-move"
            onMouseDown={handleMouseDown}
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
            onMouseLeave={handleMouseUp}
          />
        </div>

        <div className="space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Zoom: {Math.round(scale * 100)}%</span>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setScale(Math.max(0.5, scale - 0.1))}
                >
                  <ZoomOut className="h-4 w-4" />
                </Button>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setScale(Math.min(2, scale + 0.1))}
                >
                  <ZoomIn className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <Slider
              value={[scale]}
              onValueChange={([v]) => setScale(v)}
              min={0.5}
              max={2}
              step={0.1}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Rotation: {rotation}°</span>
              <Button
                variant="outline"
                size="icon"
                onClick={() => setRotation((rotation + 90) % 360)}
              >
                <RotateCw className="h-4 w-4" />
              </Button>
            </div>
            <Slider
              value={[rotation]}
              onValueChange={([v]) => setRotation(v)}
              min={0}
              max={360}
              step={90}
            />
          </div>

          <Button
            variant="outline"
            className="w-full"
            onClick={() => {
              setPosition({ x: 0, y: 0 });
              setScale(1);
              setRotation(0);
            }}
          >
            <Move className="h-4 w-4 mr-2" />
            Reset Position
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

